const DATA=window.MODPICKER_DATA;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={vehicleId:"z3-2000-28",goal:"balanced",category:"All",query:"",sort:"recommended",hideUnverified:false,build:[],compare:[],route:"catalog"};
const goalWeights={balanced:{overall:.35,reliability:.2,quality:.15,power:.12,handling:.08,value:.1},reliability:{overall:.15,reliability:.35,quality:.2,power:.03,handling:.02,value:.15,confidence:.1},power:{overall:.15,reliability:.1,quality:.1,power:.4,handling:.02,value:.13,confidence:.1},handling:{overall:.15,reliability:.08,quality:.12,power:.02,handling:.43,value:.12,confidence:.08},track:{overall:.18,reliability:.17,quality:.15,power:.2,handling:.2,value:.05,confidence:.05},budget:{overall:.15,reliability:.15,quality:.08,power:.1,handling:.1,value:.37,confidence:.05}};
function boot(){loadState();parseShare();bind();renderAll()}
function loadState(){try{Object.assign(state,JSON.parse(localStorage.getItem("modpicker-state")||"{}"))}catch(e){}}
function saveState(){localStorage.setItem("modpicker-state",JSON.stringify({vehicleId:state.vehicleId,goal:state.goal,build:state.build,compare:state.compare}))}
function vehicle(){return DATA.vehicles.find(v=>v.id===state.vehicleId)||DATA.vehicles[0]}
function part(id){return DATA.parts.find(p=>p.id===id)}
function compatibleParts(){return DATA.parts.filter(p=>p.vehicles.includes(state.vehicleId))}
function lowestPrice(p){return Math.min(...p.offers.map(o=>o.price))}
function money(n){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:n%1?2:0}).format(n)}
function goalScore(p){const w=goalWeights[state.goal];let score=0,total=0;for(const[k,weight]of Object.entries(w)){const val=k==="confidence"?p.confidence/10:(p.rating[k]??p.rating.overall);score+=val*weight;total+=weight}if(p.goalTags.includes(state.goal))score+=.25;return Math.min(10,score/total)}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),1500)}
function bind(){
$("#vehicleSelect").addEventListener("change",e=>{state.vehicleId=e.target.value;state.category="All";state.compare=[];state.build=state.build.filter(id=>part(id)?.vehicles.includes(state.vehicleId));saveState();renderAll()});
$("#goalSelect").addEventListener("change",e=>{state.goal=e.target.value;saveState();renderAll()});
$("#searchInput").addEventListener("input",e=>{state.query=e.target.value;renderCatalog()});
$("#categoryFilter").addEventListener("change",e=>{state.category=e.target.value;renderCatalog()});
$("#sortSelect").addEventListener("change",e=>{state.sort=e.target.value;renderCatalog()});
$("#hideUnverified").addEventListener("change",e=>{state.hideUnverified=e.target.checked;renderCatalog()});
$$('[data-route]').forEach(el=>el.addEventListener('click',()=>route(el.dataset.route)));
$("#mobileMenuButton").addEventListener("click",()=>$(".main-nav").classList.toggle("open"));
$("#dialogClose").addEventListener("click",()=>$("#partDialog").close());
$("#clearBuildButton").addEventListener("click",()=>{state.build=[];saveState();renderAll();toast("Build cleared")});
$("#copyBuildButton").addEventListener("click",copyBuild);$("#shareBuildButton").addEventListener("click",shareBuild)}
function route(name){state.route=name;$$('.view').forEach(v=>v.classList.remove('active-view'));$(`#${name}View`).classList.add('active-view');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.route===name));$('.main-nav').classList.remove('open');if(name==='rankings')renderRankings();if(name==='compare')renderCompare();if(name==='build')renderBuild();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderVehicle();renderCatalog();renderCounts();renderRankings();renderCompare();renderBuild()}
function renderVehicle(){const v=vehicle();$("#vehicleSelect").innerHTML=DATA.vehicles.map(x=>`<option value="${x.id}" ${x.id===v.id?'selected':''}>${x.year} ${x.make} ${x.model} ${x.trim}</option>`).join('');$("#goalSelect").value=state.goal;$("#vehicleName").textContent=`${v.year} ${v.make} ${v.model} ${v.trim}`;$("#vehicleBadges").innerHTML=v.tags.map(t=>`<span class="badge">${t}</span>`).join('');$("#fitmentSummary").textContent=`${v.chassis} · ${v.engine}`;const cp=compatibleParts();$("#heroCompatible").textContent=cp.length;$("#heroCategories").textContent=new Set(cp.map(p=>p.category)).size;$("#heroOffers").textContent=cp.reduce((s,p)=>s+p.offers.length,0)}
function categories(){return["All",...new Set(compatibleParts().map(p=>p.category))]}
function filtered(){let list=compatibleParts();if(state.category!=="All")list=list.filter(p=>p.category===state.category);const q=state.query.trim().toLowerCase();if(q)list=list.filter(p=>[p.brand,p.name,p.category,...p.tags].join(' ').toLowerCase().includes(q));if(state.hideUnverified)list=list.filter(p=>p.confidence>=70);const sorters={recommended:(a,b)=>goalScore(b)-goalScore(a),rating:(a,b)=>b.rating.overall-a.rating.overall,"price-low":(a,b)=>lowestPrice(a)-lowestPrice(b),"price-high":(a,b)=>lowestPrice(b)-lowestPrice(a),reliability:(a,b)=>b.rating.reliability-a.rating.reliability,power:(a,b)=>b.rating.power-a.rating.power,value:(a,b)=>b.rating.value-a.rating.value};return list.sort(sorters[state.sort])}
function renderCatalog(){const cats=categories();$("#categoryFilter").innerHTML=cats.map(c=>`<option ${c===state.category?'selected':''}>${c}</option>`).join('');$("#categoryButtons").innerHTML=cats.map(c=>`<button class="category-button ${c===state.category?'active':''}" onclick="setCategory('${c.replaceAll("'","\\'")}')"><span>${c}</span><span>${c==='All'?compatibleParts().length:compatibleParts().filter(p=>p.category===c).length}</span></button>`).join('');const list=filtered();$("#resultCount").textContent=`${list.length} results`;$("#catalogTitle").textContent=state.category==='All'?'Compatible parts':state.category;$("#partGrid").innerHTML=list.length?list.map(card).join(''):`<div class="empty-state">No parts match the current filters.</div>`}
function scoreRow(label,val){return`<div class="score-row"><span>${label}</span><div class="score-track"><span style="width:${val*10}%"></span></div><strong>${val.toFixed(1)}</strong></div>`}
function card(p){const added=state.build.includes(p.id),comp=state.compare.includes(p.id);return`<article class="part-card"><div class="part-top"><div><div class="part-brand">${p.brand} · ${p.category}</div><div class="part-name">${p.name}</div></div><div class="score-chip">${p.rating.overall.toFixed(1)}</div></div><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="fitment-line"><span class="fit-dot"></span>Fits selected ${vehicle().model}</div><div class="score-list">${scoreRow('Quality',p.rating.quality)}${scoreRow('Reliability',p.rating.reliability)}${scoreRow(state.goal==='handling'?'Handling':'Performance',state.goal==='handling'?p.rating.handling:p.rating.power)}${scoreRow('Value',p.rating.value)}</div><div class="part-price-row"><div class="price-block"><small>from ${p.offers.length} seller${p.offers.length!==1?'s':''}</small><strong>${money(lowestPrice(p))}</strong><div class="offer-count">Confidence ${p.confidence}%</div></div><div class="card-actions"><button class="button secondary small compare-toggle ${comp?'selected':''}" onclick="toggleCompare('${p.id}')">${comp?'Comparing':'Compare'}</button><button class="button secondary small" onclick="showPart('${p.id}')">Details</button><button class="button primary small" onclick="toggleBuild('${p.id}')">${added?'Added':'Add'}</button></div></div></article>`}
function setCategory(c){state.category=c;renderCatalog()}
function toggleBuild(id){state.build.includes(id)?state.build=state.build.filter(x=>x!==id):state.build.push(id);saveState();renderCatalog();renderCounts();renderBuild();toast(state.build.includes(id)?'Added to build':'Removed from build')}
function toggleCompare(id){if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else{if(state.compare.length>=4)return toast('Compare supports up to 4 parts');state.compare.push(id)}saveState();renderCatalog();renderCounts();renderCompare()}
function renderCounts(){$("#buildNavCount").textContent=state.build.length;$("#compareNavCount").textContent=state.compare.length}
function goalLabel(){return{balanced:'Balanced',reliability:'Reliability',power:'Power',handling:'Handling',track:'Track',budget:'Budget'}[state.goal]}
function renderRankings(){const list=[...compatibleParts()].sort((a,b)=>goalScore(b)-goalScore(a)),avg=list.length?list.reduce((s,p)=>s+p.rating.overall,0)/list.length:0,best=list[0],trusted=[...list].sort((a,b)=>b.confidence-a.confidence)[0];$("#rankingSummary").innerHTML=`<div><span>Goal</span><strong>${goalLabel()}</strong></div><div><span>Top ranked</span><strong>${best?best.brand:'—'}</strong></div><div><span>Catalog avg.</span><strong>${avg.toFixed(1)}</strong></div><div><span>Highest confidence</span><strong>${trusted?trusted.confidence+'%':'—'}</strong></div>`;$("#rankingTable").innerHTML=`<div class="ranking-row header"><div>Rank</div><div>Part</div><div>Goal score</div><div>Rating</div><div>Reliability</div><div>Price</div><div></div></div>`+list.map((p,i)=>`<div class="ranking-row"><div class="rank-number">#${i+1}</div><div class="rank-part"><strong>${p.brand} ${p.name}</strong><small>${p.category}</small></div><div class="metric-cell"><strong>${goalScore(p).toFixed(1)}</strong><span>${goalLabel()}</span></div><div class="metric-cell"><strong>${p.rating.overall.toFixed(1)}</strong><span>overall</span></div><div class="metric-cell"><strong>${p.rating.reliability.toFixed(1)}</strong><span>reliability</span></div><div class="metric-cell"><strong>${money(lowestPrice(p))}</strong><span>from</span></div><div><button class="button secondary small" onclick="showPart('${p.id}')">View</button></div></div>`).join('')}
function renderCompare(){const ps=state.compare.map(part).filter(Boolean);$("#compareEmpty").style.display=ps.length?'none':'block';$("#compareEmpty").innerHTML=`<strong>No parts selected.</strong><br>Add parts using the Compare button in the catalog.`;if(!ps.length){$("#compareTableWrap").innerHTML='';return}const row=(label,fn)=>`<div class="compare-row" style="--cols:${ps.length}"><div class="compare-cell compare-label">${label}</div>${ps.map(p=>`<div class="compare-cell">${fn(p)}</div>`).join('')}</div>`;$("#compareTableWrap").innerHTML=`<div class="compare-table">${row('Part',p=>`<div class="compare-part-head"><span class="eyebrow">${p.brand}</span><strong>${p.name}</strong><small>${p.category}</small><br><button class="button secondary small" style="margin-top:12px" onclick="toggleCompare('${p.id}')">Remove</button></div>`)}${row('Lowest price',p=>`<strong>${money(lowestPrice(p))}</strong><br><small>${p.offers.length} offers</small>`)}${row('Overall',p=>`<strong>${p.rating.overall.toFixed(1)}/10</strong>`)}${row('Reliability',p=>`<strong>${p.rating.reliability.toFixed(1)}/10</strong>`)}${row('Power',p=>`<strong>${p.rating.power.toFixed(1)}/10</strong><br><small>~${p.powerImpact?p.powerImpact+' hp':'supporting mod'}</small>`)}${row('Handling',p=>`<strong>${p.rating.handling.toFixed(1)}/10</strong>`)}${row('Value',p=>`<strong>${p.rating.value.toFixed(1)}/10</strong>`)}${row('Confidence',p=>`<strong>${p.confidence}%</strong>`)}${row('Requires',p=>p.requires.length?p.requires.map(id=>part(id)?.name||id).join('<br>'):'None')}${row('Fitment',p=>p.fitment)}</div>`}
function buildIssues(){const issues=[],selected=new Set(state.build);state.build.map(part).filter(Boolean).forEach(p=>{p.requires.forEach(req=>{if(!selected.has(req))issues.push(`${p.name} requires ${part(req)?.name||req}.`)});p.conflicts.forEach(conf=>{if(selected.has(conf)&&p.id<conf)issues.push(`${p.name} conflicts with ${part(conf)?.name||conf}.`)})});return issues}
function renderBuild(){const ps=state.build.map(part).filter(Boolean),issues=buildIssues();$("#buildTitle").textContent=`${vehicle().year} ${vehicle().make} ${vehicle().model} build`;$("#compatibilityPanel").innerHTML=issues.length?`<div class="compat-card warn"><h3>Compatibility attention needed</h3><ul>${issues.map(i=>`<li>${i}</li>`).join('')}</ul></div>`:`<div class="compat-card good"><h3>${ps.length?'Build compatibility looks good':'Start your build'}</h3><p>${ps.length?'No known conflicts or missing supporting modifications are detected in this prototype ruleset.':'Add parts from the catalog. ModPicker will track cost, category coverage, dependencies and known conflicts.'}</p></div>`;const cats=[...new Set(ps.map(p=>p.category))];$("#buildCategories").innerHTML=ps.length?cats.map(c=>{const arr=ps.filter(p=>p.category===c);return`<div class="build-category"><div class="build-category-head"><strong>${c}</strong><span>${arr.length} part${arr.length!==1?'s':''}</span></div>${arr.map(p=>`<div class="build-item"><div><strong>${p.brand} ${p.name}</strong><small>${p.fitment}</small></div><div>${p.rating.overall.toFixed(1)}/10</div><div><strong>${money(lowestPrice(p))}</strong><small>lowest offer</small></div><button class="button danger small" onclick="toggleBuild('${p.id}')">×</button></div>`).join('')}</div>`}).join(''):`<div class="empty-state">Your build sheet is empty. Add compatible parts from the catalog.</div>`;const total=ps.reduce((s,p)=>s+lowestPrice(p),0),avg=ps.length?ps.reduce((s,p)=>s+p.rating.overall,0)/ps.length:0,power=ps.reduce((s,p)=>s+p.powerImpact,0),conf=ps.length?Math.round(ps.reduce((s,p)=>s+p.confidence,0)/ps.length):0,gs=ps.length?ps.reduce((s,p)=>s+goalScore(p),0)/ps.length:0;$("#buildTotal").textContent=money(total);$("#buildPartCount").textContent=ps.length;$("#buildAvgRating").textContent=ps.length?avg.toFixed(1):'—';$("#buildPowerImpact").textContent=ps.length?`~+${power} hp`:'—';$("#buildConfidence").textContent=ps.length?`${conf}%`:'—';$("#buildGoalScore").innerHTML=`<span>${goalLabel()} build score</span><strong>${ps.length?gs.toFixed(1)+'/10':'—'}</strong>`}
function showPart(id){const p=part(id),req=p.requires.length?p.requires.map(id=>part(id)?.name||id).join(', '):'None',conf=p.conflicts.length?p.conflicts.map(id=>part(id)?.name||id).join(', '):'None';$("#partDialogContent").innerHTML=`<div class="dialog-title"><span class="eyebrow">${p.brand} · ${p.category}</span><h2>${p.name}</h2><p class="dialog-sub">${p.summary}</p></div><div class="dialog-grid"><div class="dialog-box"><h3>Rating breakdown</h3>${scoreRow('Overall',p.rating.overall)}${scoreRow('Quality',p.rating.quality)}${scoreRow('Reliability',p.rating.reliability)}${scoreRow('Power',p.rating.power)}${scoreRow('Handling',p.rating.handling)}${scoreRow('Value',p.rating.value)}<p class="fine-print">Evidence confidence: ${p.confidence}%</p></div><div class="dialog-box"><h3>Fitment & compatibility</h3><p>${p.fitment}</p><p><strong>Requires:</strong> ${req}</p><p><strong>Conflicts:</strong> ${conf}</p><button class="button primary" onclick="toggleBuild('${p.id}')">${state.build.includes(p.id)?'Remove from build':'Add to build'}</button></div></div><div class="dialog-grid"><div class="dialog-box"><h3>Pros</h3><ul>${p.pros.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="dialog-box"><h3>Tradeoffs</h3><ul>${p.cons.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><h3>Price comparison</h3><div class="offer-list">${[...p.offers].sort((a,b)=>a.price-b.price).map((o,i)=>`<div class="offer"><div><strong>${o.seller}</strong><small>${o.shipping}</small></div><strong>${money(o.price)}</strong><a href="${o.url}" target="_blank" rel="noopener">${i===0?'Lowest / search':'Check price'}</a></div>`).join('')}</div><h3 style="margin-top:24px">Evidence notes</h3><div class="evidence-list">${p.evidence.map(e=>`<div class="evidence-item"><strong>${e.type}</strong><p>${e.summary}</p></div>`).join('')}</div><div class="warning-box" style="margin-top:14px">Prototype data: pricing is a seed snapshot/search aid, not a guaranteed live quote. Production should refresh offers and evidence automatically.</div>`;$("#partDialog").showModal()}
async function copyBuild(){const ps=state.build.map(part).filter(Boolean),lines=[`ModPicker Build — ${vehicle().year} ${vehicle().make} ${vehicle().model} ${vehicle().trim}`,`Goal: ${goalLabel()}`,'',...ps.map(p=>`- ${p.category}: ${p.brand} ${p.name} — ${money(lowestPrice(p))} — ${p.rating.overall.toFixed(1)}/10`),'',`Estimated total: ${money(ps.reduce((s,p)=>s+lowestPrice(p),0))}`];await navigator.clipboard.writeText(lines.join('\n'));toast('Build summary copied')}
async function shareBuild(){const payload=btoa(unescape(encodeURIComponent(JSON.stringify({v:state.vehicleId,g:state.goal,b:state.build}))));const url=`${location.origin}${location.pathname}#build=${payload}`;await navigator.clipboard.writeText(url);toast('Share link copied')}
function parseShare(){if(!location.hash.startsWith('#build='))return;try{const obj=JSON.parse(decodeURIComponent(escape(atob(location.hash.slice(7)))));if(DATA.vehicles.some(v=>v.id===obj.v))state.vehicleId=obj.v;if(goalWeights[obj.g])state.goal=obj.g;if(Array.isArray(obj.b))state.build=obj.b.filter(id=>part(id));state.route='build';setTimeout(()=>route('build'),0)}catch(e){}}
window.setCategory=setCategory;window.toggleBuild=toggleBuild;window.toggleCompare=toggleCompare;window.showPart=showPart;boot();