(()=>{
const D=window.MODPICKER_DATA;
const enc=encodeURIComponent;
const vendors={bmw:["FCP Euro","BimmerWorld","Turner Motorsport"],jdm:["Summit Racing","Good-Win Racing","JEGS"],general:["Summit Racing","Tire Rack","JEGS"],euro:["FCP Euro","ECS Tuning","USP Motorsports"],mustang:["CJ Pony Parts","AmericanMuscle","Lethal Performance"]};
const searchUrl=(seller,q)=>`https://www.google.com/search?q=${enc(`${seller} ${q}`)}`;
const offers=(brand,name,price,set="general")=>vendors[set].map((seller,i)=>({seller,price:Math.round((price*(1+[0,.045,-.028][i]))*100)/100,shipping:i===0?"Check site":i===1?"Varies":"Check site",status:"Verify",url:searchUrl(seller,`${brand} ${name}`)}));
function add(s){
 const [quality,reliability,power,handling,value,confidence]=s.scores;
 const overall=Math.round((quality*.23+reliability*.25+power*.16+handling*.16+value*.20)*10)/10;
 D.parts.push({id:s.id,brand:s.brand,name:s.name,category:s.category,vehicles:[s.vehicle],fitment:s.fitment||`Prototype catalog entry for the selected vehicle. Verify exact SKU, production date, options and emissions legality before purchase.`,rating:{overall,quality,reliability,power,handling,value},confidence,powerImpact:s.hp||0,goalTags:s.goals||["balanced"],tags:s.tags||[s.category],requires:s.requires||[],recommended:s.recommended||[],conflicts:s.conflicts||[],summary:s.summary||`${s.name} is included as a prototype catalog option for comparison, pricing and build-planning workflows.`,pros:s.pros||["Adds another build-path option","Comparable by price and goal score"],cons:s.cons||["Exact application must be verified","Prototype price snapshot is not live"],install:{difficulty:s.install?.[0]||"Moderate",hours:s.install?.[1]||2},offers:offers(s.brand,s.name,s.price,s.vendorSet||"general"),evidence:[{type:"Prototype catalog seed",summary:"Ratings and prices are seeded for product-development testing and are not yet live evidence-derived values."}]});
}
const byId=id=>D.vehicles.find(v=>v.id===id);
Object.assign(byId("z3-2000-28"),{recommendedCategories:["Maintenance","Cooling","Tires","Brakes","Suspension","Chassis"]});
Object.assign(byId("miata-1999"),{recommendedCategories:["Maintenance","Tires","Brakes","Suspension","Chassis"]});
Object.assign(byId("brz-2017"),{recommendedCategories:["Maintenance","Tires","Brakes","Suspension","Cooling"]});
D.vehicles.push(
{id:"e46-2003-330i",year:2003,make:"BMW",model:"3 Series",trim:"330i",chassis:"E46",engine:"M54B30 3.0L",drivetrain:"RWD",transmission:"5-speed manual",tags:["E46","M54B30","RWD","Manual"],recommendedCategories:["Maintenance","Cooling","Tires","Brakes","Suspension","Chassis"]},
{id:"mustang-2015-gt",year:2015,make:"Ford",model:"Mustang",trim:"GT",chassis:"S550",engine:"Coyote 5.0L V8",drivetrain:"RWD",transmission:"6-speed manual",tags:["S550","5.0 V8","RWD","Manual"],recommendedCategories:["Tires","Brakes","Suspension","Drivetrain","Cooling"]},
{id:"gti-2020",year:2020,make:"Volkswagen",model:"Golf GTI",trim:"SE",chassis:"Mk7.5",engine:"EA888 Gen 3 2.0T",drivetrain:"FWD",transmission:"6-speed manual",tags:["Mk7.5","EA888","FWD","Turbo"],recommendedCategories:["Maintenance","Tires","Brakes","Cooling","Drivetrain"]}
);
// BMW Z3 2.8 expansion
add({id:"mahle-z3-thermostat",vehicle:"z3-2000-28",brand:"Mahle/Behr",name:"Thermostat & Housing Refresh",category:"Maintenance",price:92,vendorSet:"bmw",scores:[8.8,9.1,1,1,9.2,82],goals:["reliability","balanced","budget"],tags:["Maintenance","Cooling","Preventive"],install:["Moderate",2],summary:"Preventive cooling-system service item intended for an aging M52TU cooling system."});
add({id:"z3-silicone-hoses",vehicle:"z3-2000-28",brand:"Mishimoto",name:"Silicone Coolant Hose Kit",category:"Cooling",price:149,vendorSet:"bmw",scores:[8.4,8.5,1,1,8.1,66],goals:["reliability","track"],tags:["Cooling","Hoses","Refresh"],install:["Moderate",2.5]});
add({id:"z3-stoptech-pads",vehicle:"z3-2000-28",brand:"StopTech",name:"Sport Brake Pads",category:"Brakes",price:158,vendorSet:"bmw",scores:[8.6,8.4,1,4.5,8.8,77],goals:["handling","track","balanced"],tags:["Brakes","Pads","Street/Track"],install:["Moderate",2]});
add({id:"z3-zimmerman-rotors",vehicle:"z3-2000-28",brand:"Zimmermann",name:"Coated Brake Rotor Set",category:"Brakes",price:286,vendorSet:"bmw",scores:[8.9,9,1,4,8.6,80],goals:["reliability","balanced","track"],tags:["Brakes","Rotors","Refresh"],install:["Moderate",3]});
add({id:"z3-goodridge-lines",vehicle:"z3-2000-28",brand:"Goodridge",name:"Stainless Brake Line Kit",category:"Brakes",price:119,vendorSet:"bmw",scores:[8.7,8.8,1,5.7,8.5,74],goals:["handling","track"],tags:["Brakes","Lines","Pedal feel"],install:["Advanced",3]});
add({id:"z3-uuc-sway",vehicle:"z3-2000-28",brand:"UUC Motorwerks",name:"Adjustable Sway Bar Set",category:"Suspension",price:649,vendorSet:"bmw",scores:[8.8,8.5,1,9.1,7.7,66],goals:["handling","track"],tags:["Suspension","Sway bars","Adjustable"],install:["Moderate",3.5]});
add({id:"z3-ie-subframe",vehicle:"z3-2000-28",brand:"Ireland Engineering",name:"Rear Subframe Bushing Kit",category:"Chassis",price:189,vendorSet:"bmw",scores:[8.8,8.9,1,8.6,8.7,70],goals:["handling","reliability","track"],tags:["Chassis","Bushings","Rear suspension"],install:["Professional",6]});
add({id:"z3-strut-brace",vehicle:"z3-2000-28",brand:"Turner Motorsport",name:"Front Strut Tower Brace",category:"Chassis",price:329,vendorSet:"bmw",scores:[8.5,9,1,6.8,7.4,61],goals:["handling","balanced"],tags:["Chassis","Brace","Bolt-on"],install:["Easy",0.5]});
add({id:"z3-short-shifter",vehicle:"z3-2000-28",brand:"Rogue Engineering",name:"Short Shift Kit",category:"Drivetrain",price:365,vendorSet:"bmw",scores:[8.9,8.7,1,4.8,8,68],goals:["balanced","track"],tags:["Drivetrain","Shifter","Driver feel"],install:["Advanced",3]});
add({id:"z3-apex-wheels",vehicle:"z3-2000-28",brand:"APEX",name:"ARC-8 Wheel Set",category:"Wheels",price:1496,vendorSet:"bmw",scores:[9.1,8.8,1,8.9,8.1,78],goals:["handling","track","balanced"],tags:["Wheels","Lightweight","Fitment"],install:["Easy",1],summary:"Lightweight wheel-set option; exact width, offset and tire package must be selected for the car."});
add({id:"z3-conti-ecs02",vehicle:"z3-2000-28",brand:"Continental",name:"ExtremeContact Sport 02 Tire Set",category:"Tires",price:920,vendorSet:"general",scores:[9.1,8.8,1,9.4,8.5,84],goals:["handling","track","balanced"],tags:["Tires","Summer","Grip"],install:["Professional",1.5]});
add({id:"z3-ngk-plugs",vehicle:"z3-2000-28",brand:"NGK",name:"Laser Platinum Spark Plug Set",category:"Ignition",price:58,vendorSet:"bmw",scores:[8.9,9.2,2,1,9.4,85],goals:["reliability","budget","balanced"],tags:["Ignition","Maintenance","Tune-up"],install:["Easy",1]});
add({id:"z3-bosch-coils",vehicle:"z3-2000-28",brand:"Bosch",name:"Ignition Coil Set",category:"Ignition",price:239,vendorSet:"bmw",scores:[8.8,9,2,1,8.7,82],goals:["reliability","balanced"],tags:["Ignition","Maintenance","Coils"],install:["Easy",1]});

// NB Miata expansion
add({id:"miata-fm-sway",vehicle:"miata-1999",brand:"Flyin' Miata",name:"Sway Bar Set",category:"Suspension",price:399,vendorSet:"jdm",scores:[9,8.8,1,9.4,8.6,79],goals:["handling","track","balanced"],tags:["Suspension","Sway bars","Miata"],install:["Moderate",3]});
add({id:"miata-koni",vehicle:"miata-1999",brand:"Koni",name:"Sport Adjustable Shocks",category:"Suspension",price:690,vendorSet:"jdm",scores:[9,8.8,1,9.2,8.5,80],goals:["handling","track","balanced"],tags:["Suspension","Damper","Adjustable"],install:["Advanced",5]});
add({id:"miata-eibach",vehicle:"miata-1999",brand:"Eibach",name:"Pro-Kit Springs",category:"Suspension",price:309,vendorSet:"jdm",scores:[8.8,8.8,1,8.5,8.7,75],goals:["handling","budget","balanced"],tags:["Suspension","Springs","Lowering"],install:["Advanced",5]});
add({id:"miata-rs-exhaust",vehicle:"miata-1999",brand:"RoadsterSport",name:"Cat-Back Exhaust",category:"Exhaust",price:629,vendorSet:"jdm",scores:[8.8,8.7,5.8,1,8,71],hp:4,goals:["power","balanced"],tags:["Exhaust","Sound","Stainless"],install:["Moderate",1.5]});
add({id:"miata-racingbeat-intake",vehicle:"miata-1999",brand:"Racing Beat",name:"High Flow Intake",category:"Intake",price:289,vendorSet:"jdm",scores:[8.5,8.5,4.8,1,7.8,63],hp:3,goals:["power","balanced"],tags:["Intake","Bolt-on","Sound"],install:["Easy",1]});
add({id:"miata-wilwood",vehicle:"miata-1999",brand:"Wilwood",name:"Front Big Brake Kit",category:"Brakes",price:1149,vendorSet:"jdm",scores:[9.1,8.6,1,8.7,7.8,74],goals:["track","handling"],tags:["Brakes","Big brake kit","Track"],install:["Advanced",4]});
add({id:"miata-enkei-rpf1",vehicle:"miata-1999",brand:"Enkei",name:"RPF1 Wheel Set",category:"Wheels",price:1080,vendorSet:"general",scores:[9.3,9,1,9.2,8.7,87],goals:["handling","track","balanced"],tags:["Wheels","Lightweight","Motorsport"],install:["Easy",1]});
add({id:"miata-conti-ecs02",vehicle:"miata-1999",brand:"Continental",name:"ExtremeContact Sport 02 Tire Set",category:"Tires",price:670,vendorSet:"general",scores:[9.1,8.8,1,9.5,8.8,85],goals:["handling","track","balanced"],tags:["Tires","Summer","Grip"],install:["Professional",1.5]});
add({id:"miata-exedy-clutch",vehicle:"miata-1999",brand:"Exedy",name:"OEM Replacement Clutch Kit",category:"Drivetrain",price:355,vendorSet:"jdm",scores:[8.9,9,3,1,9,82],goals:["reliability","balanced","budget"],tags:["Drivetrain","Clutch","Refresh"],install:["Professional",7]});
add({id:"miata-frame-rails",vehicle:"miata-1999",brand:"Flyin' Miata",name:"Frame Rail Reinforcement Kit",category:"Chassis",price:219,vendorSet:"jdm",scores:[8.8,9,1,8.2,9,78],goals:["handling","track","balanced"],tags:["Chassis","Reinforcement","Miata"],install:["Advanced",4]});

// BRZ expansion
add({id:"brz-ecutek",vehicle:"brz-2017",brand:"EcuTek",name:"ECU Calibration Package",category:"Tuning",price:749,vendorSet:"jdm",scores:[8.7,8.3,8.6,1,8.1,72],hp:12,goals:["power","balanced"],tags:["Tuning","ECU","FA20"],install:["Advanced",1.5],recommended:["brz-header"]});
add({id:"brz-perrin-intake",vehicle:"brz-2017",brand:"PERRIN",name:"Cold Air Intake",category:"Intake",price:369,vendorSet:"jdm",scores:[8.7,8.6,5,1,7.5,69],hp:4,goals:["power","balanced"],tags:["Intake","Bolt-on","FA20"],install:["Easy",1]});
add({id:"brz-invidia-q300",vehicle:"brz-2017",brand:"Invidia",name:"Q300 Cat-Back Exhaust",category:"Exhaust",price:819,vendorSet:"jdm",scores:[8.9,8.7,5.8,1,8,78],hp:4,goals:["power","balanced"],tags:["Exhaust","Cat-back","Street"],install:["Moderate",1.5]});
add({id:"brz-jr-oilcooler",vehicle:"brz-2017",brand:"Jackson Racing",name:"Engine Oil Cooler Kit",category:"Cooling",price:849,vendorSet:"jdm",scores:[9,8.9,2,1,8.4,76],goals:["track","reliability"],tags:["Cooling","Oil","Track"],install:["Advanced",4]});
add({id:"brz-whiteline-sway",vehicle:"brz-2017",brand:"Whiteline",name:"Adjustable Sway Bar Kit",category:"Suspension",price:529,vendorSet:"jdm",scores:[8.8,8.7,1,9.1,8.5,77],goals:["handling","track"],tags:["Suspension","Sway bars","Adjustable"],install:["Moderate",3]});
add({id:"brz-csg-pads",vehicle:"brz-2017",brand:"CSG",name:"Spec Brake Pad Set",category:"Brakes",price:365,vendorSet:"jdm",scores:[9.1,8.7,1,8.8,8.2,75],goals:["track","handling"],tags:["Brakes","Pads","Track"],install:["Moderate",2]});
add({id:"brz-enkei-rpf1",vehicle:"brz-2017",brand:"Enkei",name:"RPF1 Wheel Set",category:"Wheels",price:1260,vendorSet:"general",scores:[9.3,9,1,9.3,8.6,87],goals:["handling","track","balanced"],tags:["Wheels","Lightweight","Motorsport"],install:["Easy",1]});
add({id:"brz-michelin-ps4s",vehicle:"brz-2017",brand:"Michelin",name:"Pilot Sport 4S Tire Set",category:"Tires",price:1010,vendorSet:"general",scores:[9.5,9,1,9.7,8.3,90],goals:["handling","track","balanced"],tags:["Tires","Summer","Grip"],install:["Professional",1.5]});
add({id:"brz-act-clutch",vehicle:"brz-2017",brand:"ACT",name:"Heavy Duty Performance Clutch",category:"Drivetrain",price:735,vendorSet:"jdm",scores:[8.7,8.4,7.5,1,8,70],goals:["power","track"],tags:["Drivetrain","Clutch","Supporting mod"],install:["Professional",7]});

// E46 330i catalog
add({id:"e46-koyo",vehicle:"e46-2003-330i",brand:"Koyorad",name:"Aluminum Radiator",category:"Cooling",price:365,vendorSet:"bmw",scores:[9.1,9,1,1,8.1,80],goals:["reliability","track","balanced"],tags:["Cooling","E46","Aluminum"],install:["Moderate",3]});
add({id:"e46-stewart",vehicle:"e46-2003-330i",brand:"Stewart Components",name:"High Performance Water Pump",category:"Cooling",price:219,vendorSet:"bmw",scores:[9.4,9.2,1,1,8,82],goals:["reliability","track"],tags:["Cooling","Pump","M54"],install:["Advanced",3]});
add({id:"e46-bilstein-b12",vehicle:"e46-2003-330i",brand:"Bilstein",name:"B12 Pro-Kit Suspension",category:"Suspension",price:1039,vendorSet:"bmw",scores:[9.2,9,1,9.3,8.4,82],goals:["handling","track","balanced"],tags:["Suspension","Matched kit","E46"],install:["Professional",6]});
add({id:"e46-powerflex-rtab",vehicle:"e46-2003-330i",brand:"Powerflex",name:"Rear Trailing Arm Bushings",category:"Chassis",price:125,vendorSet:"bmw",scores:[8.9,8.9,1,8.6,9,80],goals:["handling","reliability","balanced"],tags:["Chassis","Bushings","E46"],install:["Advanced",4]});
add({id:"e46-stoptech",vehicle:"e46-2003-330i",brand:"StopTech",name:"Sport Brake Upgrade Package",category:"Brakes",price:879,vendorSet:"bmw",scores:[9,8.8,1,8.7,8,76],goals:["track","handling","balanced"],tags:["Brakes","Rotors","Pads"],install:["Advanced",4]});
add({id:"e46-afe",vehicle:"e46-2003-330i",brand:"aFe Power",name:"Magnum FORCE Intake",category:"Intake",price:395,vendorSet:"bmw",scores:[8.6,8.5,5.4,1,7.3,66],hp:4,goals:["power","balanced"],tags:["Intake","M54","Bolt-on"],install:["Easy",1]});
add({id:"e46-magnaflow",vehicle:"e46-2003-330i",brand:"MagnaFlow",name:"Performance Cat-Back Exhaust",category:"Exhaust",price:1095,vendorSet:"bmw",scores:[8.8,8.7,5.9,1,7.2,68],hp:5,goals:["power","balanced"],tags:["Exhaust","Stainless","E46"],install:["Moderate",2]});
add({id:"e46-conti",vehicle:"e46-2003-330i",brand:"Continental",name:"ExtremeContact Sport 02 Tire Set",category:"Tires",price:910,scores:[9.1,8.8,1,9.4,8.5,85],goals:["handling","track","balanced"],tags:["Tires","Summer","Grip"],install:["Professional",1.5]});

// S550 Mustang GT catalog
add({id:"mustang-steeda-intake",vehicle:"mustang-2015-gt",brand:"Steeda",name:"ProFlow Cold Air Intake",category:"Intake",price:429,vendorSet:"mustang",scores:[8.9,8.7,6.8,1,8,73],hp:8,goals:["power","balanced"],tags:["Intake","Coyote","Bolt-on"],install:["Easy",1]});
add({id:"mustang-corsa",vehicle:"mustang-2015-gt",brand:"Corsa",name:"Sport Cat-Back Exhaust",category:"Exhaust",price:1899,vendorSet:"mustang",scores:[9.3,9,6.6,1,7.2,80],hp:6,goals:["power","balanced"],tags:["Exhaust","Sound","Stainless"],install:["Moderate",2]});
add({id:"mustang-bmr-springs",vehicle:"mustang-2015-gt",brand:"BMR",name:"Performance Lowering Springs",category:"Suspension",price:289,vendorSet:"mustang",scores:[8.8,8.8,1,8.8,9,77],goals:["handling","budget","balanced"],tags:["Suspension","Springs","S550"],install:["Professional",5]});
add({id:"mustang-fp-shocks",vehicle:"mustang-2015-gt",brand:"Ford Performance",name:"Track Shock & Strut Kit",category:"Suspension",price:825,vendorSet:"mustang",scores:[9.1,9.1,1,9.2,8.4,81],goals:["handling","track"],tags:["Suspension","Damper","Track"],install:["Professional",5]});
add({id:"mustang-mgw",vehicle:"mustang-2015-gt",brand:"MGW",name:"Race Spec Short Throw Shifter",category:"Drivetrain",price:499,vendorSet:"mustang",scores:[9.4,9.2,1,4.5,8.4,83],goals:["balanced","track"],tags:["Drivetrain","Shifter","Manual"],install:["Advanced",3]});
add({id:"mustang-brembo",vehicle:"mustang-2015-gt",brand:"Brembo",name:"GT Front Brake Kit",category:"Brakes",price:3895,vendorSet:"mustang",scores:[9.6,9.3,1,9.2,6.8,84],goals:["track","handling"],tags:["Brakes","Big brake kit","Track"],install:["Professional",5]});
add({id:"mustang-michelin",vehicle:"mustang-2015-gt",brand:"Michelin",name:"Pilot Sport 4S Tire Set",category:"Tires",price:1390,scores:[9.5,9,1,9.7,8.2,91],goals:["handling","track","balanced"],tags:["Tires","Summer","Grip"],install:["Professional",1.5]});
add({id:"mustang-oilcooler",vehicle:"mustang-2015-gt",brand:"Mishimoto",name:"Performance Oil Cooler Kit",category:"Cooling",price:699,vendorSet:"mustang",scores:[8.8,8.8,1,1,8,72],goals:["track","reliability"],tags:["Cooling","Oil","Track"],install:["Advanced",4]});

// Mk7.5 GTI catalog
add({id:"gti-apr-stage1",vehicle:"gti-2020",brand:"APR",name:"Stage 1 ECU Software",category:"Tuning",price:599,vendorSet:"euro",scores:[9,8.3,9.4,1,9.1,78],hp:70,goals:["power","balanced"],tags:["Tuning","Turbo","EA888"],install:["Professional",1],recommended:["gti-wagner-ic"],requires:[]});
add({id:"gti-ie-intake",vehicle:"gti-2020",brand:"Integrated Engineering",name:"Cold Air Intake",category:"Intake",price:399,vendorSet:"euro",scores:[9,8.8,6.2,1,8.2,77],hp:6,goals:["power","balanced"],tags:["Intake","Turbo","Mk7"],install:["Easy",1]});
add({id:"gti-awe-exhaust",vehicle:"gti-2020",brand:"AWE",name:"Touring Edition Cat-Back",category:"Exhaust",price:1045,vendorSet:"euro",scores:[9.2,8.9,5.5,1,7.6,76],hp:4,goals:["power","balanced"],tags:["Exhaust","Touring","Mk7"],install:["Moderate",2]});
add({id:"gti-wagner-ic",vehicle:"gti-2020",brand:"Wagner Tuning",name:"Competition Intercooler",category:"Cooling",price:899,vendorSet:"euro",scores:[9.1,9,7.3,1,8.2,79],hp:5,goals:["power","track","reliability"],tags:["Cooling","Intercooler","Turbo"],install:["Advanced",5]});
add({id:"gti-bilstein-b16",vehicle:"gti-2020",brand:"Bilstein",name:"B16 Coilover Kit",category:"Suspension",price:1899,vendorSet:"euro",scores:[9.4,9.1,1,9.5,7.9,83],goals:["handling","track"],tags:["Suspension","Coilover","Adjustable"],install:["Professional",6]});
add({id:"gti-hr-sway",vehicle:"gti-2020",brand:"H&R",name:"Rear Sway Bar",category:"Suspension",price:319,vendorSet:"euro",scores:[8.9,8.9,1,9,8.9,81],goals:["handling","balanced"],tags:["Suspension","Sway bar","FWD"],install:["Moderate",2]});
add({id:"gti-stoptech",vehicle:"gti-2020",brand:"StopTech",name:"Sport Brake Package",category:"Brakes",price:925,vendorSet:"euro",scores:[9,8.8,1,8.7,8.1,76],goals:["track","handling","balanced"],tags:["Brakes","Pads","Rotors"],install:["Advanced",4]});
add({id:"gti-southbend",vehicle:"gti-2020",brand:"South Bend Clutch",name:"Stage 2 Daily Clutch Kit",category:"Drivetrain",price:1299,vendorSet:"euro",scores:[8.9,8.6,8.2,1,8,74],goals:["power","track"],tags:["Drivetrain","Clutch","Supporting mod"],install:["Professional",8],recommended:["gti-apr-stage1"]});
add({id:"gti-michelin",vehicle:"gti-2020",brand:"Michelin",name:"Pilot Sport 4S Tire Set",category:"Tires",price:940,scores:[9.5,9,1,9.7,8.4,90],goals:["handling","track","balanced"],tags:["Tires","Summer","Grip"],install:["Professional",1.5]});
})();
