(()=>{
'use strict';
const PROFILE_KEY='modpicker-owner-garage-v1';
const MAX_PHOTOS=4;
const COMMON_MAINTENANCE=['Engine oil & filter','Engine air filter','Cabin air filter','Brake fluid','Coolant','Transmission fluid','Differential fluid','Spark plugs','Accessory belts','Brake inspection','Tire rotation / inspection'];
const PROFILE_CONTEXT_FIELDS=[['odometer','odometer'],['condition','condition'],['currentMods','current mods'],['problems','current problems'],['buildGoals','build goal'],['primaryGoal','primary goal'],['budget','budget'],['likes','likes/dislikes']];
const GOAL_METRIC={balanced:'overall',reliability:'reliability',power:'power',handling:'handling',track:'overall',budget:'value'};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
let profiles=readProfiles();
let lastVehicleId='';
let currentPlan=[];

function readProfiles(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')||{}}catch{return {}}}
function writeProfiles(){try{localStorage.setItem(PROFILE_KEY,JSON.stringify(profiles));return true}catch(e){console.warn('Garage profile storage failed',e);notify('Garage storage is full. Remove a photo or export your data.');return false}}
function notify(message){if(typeof toast==='function')return toast(message);const t=$('#toast');if(t){t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}}
function selectedVehicleId(){try{if(typeof state!=='undefined'&&state?.vehicleId)return state.vehicleId}catch{}try{return JSON.parse(localStorage.getItem('modpicker-state-v2')||'{}').vehicleId||window.MODPICKER_DATA?.vehicles?.[0]?.id||''}catch{return window.MODPICKER_DATA?.vehicles?.[0]?.id||''}}
function selectedVehicle(){const vid=selectedVehicleId();return window.MODPICKER_DATA?.vehicles?.find(v=>v.id===vid)||window.MODPICKER_DATA?.vehicles?.[0]||null}
function blankProfile(){return {nickname:'',odometer:'',condition:'Driver',budget:'',targetPower:'',primaryGoal:'balanced',reliabilityPriority:'5',comfortPriority:'3',noiseTolerance:'3',currentMods:'',history:'',problems:'',likes:'',dislikes:'',buildGoals:'',photos:[],maintenance:[],codes:[],receipts:[],updatedAt:null}}
function profileFor(vehicleId=selectedVehicleId()){
 if(!vehicleId)return blankProfile();
 profiles[vehicleId]={...blankProfile(),...(profiles[vehicleId]||{})};
 for(const key of ['photos','maintenance','codes','receipts'])profiles[vehicleId][key]=Array.isArray(profiles[vehicleId][key])?profiles[vehicleId][key]:[];
 return profiles[vehicleId];
}
function saveProfile(){const p=profileFor();p.updatedAt=new Date().toISOString();writeProfiles();renderSummary()}
function vehicleLabel(v=selectedVehicle()){return v?`${v.year} ${v.make} ${v.model} ${v.trim||''}`.trim():'Selected vehicle'}
function numberOrNull(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n:null}
function addMonths(dateString,months){if(!dateString||!months)return'';const d=new Date(`${dateString}T12:00:00`);if(Number.isNaN(d.getTime()))return'';d.setMonth(d.getMonth()+Number(months));return d.toISOString().slice(0,10)}
function maintenanceDue(item,p){
 const odo=numberOrNull(p.odometer),last=numberOrNull(item.lastMileage),miles=numberOrNull(item.intervalMiles);
 const dueMileage=last!=null&&miles?last+miles:null;
 const dueDate=addMonths(item.lastDate,numberOrNull(item.intervalMonths));
 let status='Unscheduled';
 if(dueMileage!=null&&odo!=null){const remaining=dueMileage-odo;if(remaining<=0)status='Due';else if(remaining<=1000)status='Due soon';else status='Tracked'}
 if(dueDate){const days=(new Date(`${dueDate}T23:59:59`)-Date.now())/86400000;if(days<0)status='Due';else if(days<=30&&status!=='Due')status='Due soon';else if(status==='Unscheduled')status='Tracked'}
 return{dueMileage,dueDate,status};
}
function maintenanceSummary(p=profileFor()){
 const statuses=p.maintenance.map(item=>maintenanceDue(item,p).status);
 return {due:statuses.filter(x=>x==='Due').length,dueSoon:statuses.filter(x=>x==='Due soon').length,tracked:statuses.filter(x=>x==='Tracked').length,unscheduled:statuses.filter(x=>x==='Unscheduled').length,total:statuses.length};
}
function recommendationContext(vehicleId=selectedVehicleId()){
 const v=window.MODPICKER_DATA?.vehicles?.find(x=>x.id===vehicleId)||null,p=profileFor(vehicleId),summary=maintenanceSummary(p);
 return {vehicle:v?{id:v.id,year:v.year,make:v.make,model:v.model,trim:v.trim,chassis:v.chassis,engine:v.engine,transmission:v.transmission}:null,ownerContext:{nickname:p.nickname,odometer:numberOrNull(p.odometer),condition:p.condition,currentMods:p.currentMods,history:p.history,currentProblems:p.problems,likes:p.likes,dislikes:p.dislikes,buildGoals:p.buildGoals},preferences:{primaryGoal:p.primaryGoal,budget:numberOrNull(p.budget),targetPowerIncrease:numberOrNull(p.targetPower),reliabilityPriority:Number(p.reliabilityPriority)||null,comfortPriority:Number(p.comfortPriority)||null,noiseTolerance:Number(p.noiseTolerance)||null},maintenance:{summary,items:p.maintenance.map(x=>({...x,...maintenanceDue(x,p)})),codes:p.codes,receiptCount:p.receipts.length}};
}
function contextCompleteness(p=profileFor()){
 const checks=PROFILE_CONTEXT_FIELDS.map(([field,label])=>{let present=Boolean(String(p[field]??'').trim());if(field==='likes')present=Boolean(String(p.likes||'').trim()||String(p.dislikes||'').trim());return{field,label,present}});
 return {completed:checks.filter(x=>x.present).length,total:checks.length,missing:checks.filter(x=>!x.present).map(x=>x.label)};
}
function render(){
 const v=selectedVehicle(),p=profileFor();if(!v)return;lastVehicleId=v.id;
 $('#garageVehicleTitle').textContent=p.nickname||vehicleLabel(v);$('#garageVehicleMeta').textContent=[vehicleLabel(v),v.engine,v.transmission,v.chassis].filter(Boolean).join(' · ');
 const fields={garageNickname:p.nickname,garageOdometer:p.odometer,garageCondition:p.condition,garageBudget:p.budget,garageTargetPower:p.targetPower,garagePrimaryGoal:p.primaryGoal,garageReliabilityPriority:p.reliabilityPriority,garageComfortPriority:p.comfortPriority,garageNoiseTolerance:p.noiseTolerance,garageCurrentMods:p.currentMods,garageHistory:p.history,garageProblems:p.problems,garageLikes:p.likes,garageDislikes:p.dislikes,garageBuildGoals:p.buildGoals};
 for(const [key,value] of Object.entries(fields)){const el=$(`#${key}`);if(el&&el.value!==String(value??''))el.value=value??''}
 renderPhotos();renderMaintenance();renderCodes();renderReceipts();renderSummary();renderPlan();
}
function renderSummary(){
 const p=profileFor(),v=selectedVehicle();if(!v)return;const context=recommendationContext(),complete=contextCompleteness(p),summary=maintenanceSummary(p);
 $('#garageProfileCompleteness').textContent=`${Math.round(complete.completed/complete.total*100)}% context complete`;
 const detail=$('#garageProfileMissing');if(detail)detail.textContent=complete.missing.length?`Add ${complete.missing.slice(0,3).join(', ')}${complete.missing.length>3?' and more':''}.`:'Core recommendation context is filled in.';
 const goals=[(p.primaryGoal||'balanced').replace(/^./,c=>c.toUpperCase())];if(p.budget)goals.push(`budget $${Number(p.budget).toLocaleString()}`);if(p.targetPower)goals.push(`target +${Number(p.targetPower).toLocaleString()} hp`);if(p.problems)goals.push('current problems recorded');
 $('#garageRecommendationSummary').textContent=`${vehicleLabel(v)} · ${goals.join(' · ')}`;
 const maint=$('#garageMaintenanceSummary');if(maint)maint.textContent=summary.total?`${summary.due} due · ${summary.dueSoon} due soon · ${summary.unscheduled} need intervals`:'No maintenance items tracked yet.';
 $('#garageContextPreview').textContent=JSON.stringify(context,null,2);
}
function renderPhotos(){const p=profileFor(),root=$('#garagePhotos');root.innerHTML=p.photos.length?p.photos.map((photo,i)=>`<figure class="garage-photo"><img src="${photo.data}" alt="${esc(photo.name||'Vehicle photo')}"/><button type="button" data-remove-photo="${i}" aria-label="Remove photo">×</button></figure>`).join(''):`<div class="garage-empty compact">Add up to ${MAX_PHOTOS} photos of the actual car. Photos stay in this browser in the current prototype.</div>`;$('#garagePhotoInput').disabled=p.photos.length>=MAX_PHOTOS;}
async function compressPhoto(file){if(!file?.type?.startsWith('image/'))throw new Error('Image file required');const url=URL.createObjectURL(file),img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url});const max=900,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);URL.revokeObjectURL(url);return await new Promise((resolve,reject)=>canvas.toBlob(blob=>{if(!blob)return reject(new Error('Image conversion failed'));const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)},'image/jpeg',.72));}
async function addPhotos(files){const p=profileFor(),slots=MAX_PHOTOS-p.photos.length;for(const file of [...files].slice(0,slots)){try{const data=await compressPhoto(file);p.photos.push({name:file.name,data,addedAt:new Date().toISOString()})}catch{notify(`Could not add ${file.name}`)}}saveProfile();renderPhotos();}
function fieldInput(e){const field=e.target.dataset.profileField;if(!field)return;profileFor()[field]=e.target.value;saveProfile();if(['primaryGoal','budget'].includes(field)){currentPlan=[];renderPlan()}}
function maintenanceRow(item,p){
 const due=maintenanceDue(item,p),statusClass=due.status.toLowerCase().replaceAll(' ','-');
 return `<article class="maintenance-card" data-maint-id="${esc(item.id)}"><div class="maintenance-card-head"><input class="maintenance-name" data-maint-field="name" value="${esc(item.name)}" placeholder="Service item"/><span class="maintenance-status ${statusClass}">${esc(due.status)}</span><div class="maintenance-actions"><button class="text-button" type="button" data-service-maint="${esc(item.id)}">Mark serviced</button><button class="text-button danger-text" type="button" data-delete-maint="${esc(item.id)}">Remove</button></div></div><div class="maintenance-grid"><label><span>Last service mileage</span><input data-maint-field="lastMileage" inputmode="numeric" type="number" min="0" value="${esc(item.lastMileage)}"></label><label><span>Interval miles</span><input data-maint-field="intervalMiles" inputmode="numeric" type="number" min="0" value="${esc(item.intervalMiles)}"></label><div class="computed-field"><span>Next mileage</span><strong>${due.dueMileage==null?'—':Number(due.dueMileage).toLocaleString()}</strong></div><label><span>Last service date</span><input data-maint-field="lastDate" type="date" value="${esc(item.lastDate)}"></label><label><span>Interval months</span><input data-maint-field="intervalMonths" inputmode="numeric" type="number" min="0" value="${esc(item.intervalMonths)}"></label><div class="computed-field"><span>Next date</span><strong>${esc(due.dueDate||'—')}</strong></div><label><span>Fluid / specification</span><input data-maint-field="fluidSpec" value="${esc(item.fluidSpec)}" placeholder="Source before filling"></label><label><span>Capacity</span><input data-maint-field="capacity" value="${esc(item.capacity)}" placeholder="Source before filling"></label><label><span>Part numbers / supplies</span><input data-maint-field="parts" value="${esc(item.parts)}" placeholder="Filter, gasket, plugs…"></label><label class="maintenance-notes"><span>Notes</span><textarea data-maint-field="notes" rows="2" placeholder="Work performed, source, observations…">${esc(item.notes)}</textarea></label></div></article>`;
}
function renderMaintenance(){const p=profileFor(),root=$('#maintenanceList');root.innerHTML=p.maintenance.length?p.maintenance.map(x=>maintenanceRow(x,p)).join(''):'<div class="garage-empty">No maintenance records yet. Add an item or create the common-service starter list.</div>';renderSummary()}
function newMaintenance(name=''){return{id:id('maint'),name,lastMileage:'',intervalMiles:'',lastDate:'',intervalMonths:'',fluidSpec:'',capacity:'',parts:'',notes:'',createdAt:new Date().toISOString()}}
function addMaintenance(name=''){profileFor().maintenance.push(newMaintenance(name));saveProfile();renderMaintenance()}
function seedMaintenance(){const p=profileFor(),existing=new Set(p.maintenance.map(x=>x.name.toLowerCase()));for(const name of COMMON_MAINTENANCE)if(!existing.has(name.toLowerCase()))p.maintenance.push(newMaintenance(name));saveProfile();renderMaintenance();notify('Starter checklist added. Vehicle-specific intervals and fluids still need sources.')}
function updateMaintenance(e){const card=e.target.closest('[data-maint-id]'),field=e.target.dataset.maintField;if(!card||!field)return;const item=profileFor().maintenance.find(x=>x.id===card.dataset.maintId);if(!item)return;item[field]=e.target.value;saveProfile();if(['lastMileage','intervalMiles','lastDate','intervalMonths'].includes(field))renderMaintenance()}
function deleteMaintenance(mid){const p=profileFor();p.maintenance=p.maintenance.filter(x=>x.id!==mid);saveProfile();renderMaintenance()}
function markServiced(mid){const p=profileFor(),item=p.maintenance.find(x=>x.id===mid);if(!item)return;item.lastDate=new Date().toISOString().slice(0,10);if(numberOrNull(p.odometer)!=null)item.lastMileage=String(numberOrNull(p.odometer));item.notes=[item.notes,`Serviced ${item.lastDate}${item.lastMileage?` at ${Number(item.lastMileage).toLocaleString()} mi`:''}.`].filter(Boolean).join(' ');saveProfile();renderMaintenance();notify(`${item.name||'Service item'} marked serviced.`)}
function addCode(){const code=$('#codeValue').value.trim().toUpperCase(),date=$('#codeDate').value,mileage=$('#codeMileage').value,description=$('#codeDescription').value.trim(),resolution=$('#codeResolution').value.trim();if(!code)return notify('Enter a diagnostic code first.');profileFor().codes.unshift({id:id('code'),code,date,mileage,description,resolution,createdAt:new Date().toISOString()});$('#codeValue').value='';$('#codeDescription').value='';$('#codeResolution').value='';saveProfile();renderCodes();}
function renderCodes(){const rows=profileFor().codes,root=$('#codeHistory');root.innerHTML=rows.length?rows.map(x=>`<div class="history-row"><div><strong>${esc(x.code)}</strong><span>${esc(x.date||'Date unknown')}${x.mileage?` · ${Number(x.mileage).toLocaleString()} mi`:''}</span></div><div><strong>${esc(x.description||'No description')}</strong><span>${esc(x.resolution||'Resolution not recorded')}</span></div><button class="text-button danger-text" data-delete-code="${esc(x.id)}">Remove</button></div>`).join(''):'<div class="garage-empty compact">No diagnostic codes recorded.</div>'}
function addReceipt(){const vendor=$('#receiptVendor').value.trim(),date=$('#receiptDate').value,amount=$('#receiptAmount').value,category=$('#receiptCategory').value.trim(),notes=$('#receiptNotes').value.trim();if(!vendor&&!notes)return notify('Add a vendor or receipt note first.');profileFor().receipts.unshift({id:id('receipt'),vendor,date,amount,category,notes,createdAt:new Date().toISOString()});$('#receiptVendor').value='';$('#receiptAmount').value='';$('#receiptCategory').value='';$('#receiptNotes').value='';saveProfile();renderReceipts();}
function renderReceipts(){const rows=profileFor().receipts,root=$('#receiptHistory');root.innerHTML=rows.length?rows.map(x=>`<div class="history-row"><div><strong>${esc(x.vendor||'Receipt')}</strong><span>${esc(x.date||'Date unknown')}${x.amount?` · $${Number(x.amount).toFixed(2)}`:''}</span></div><div><strong>${esc(x.category||'Maintenance / part purchase')}</strong><span>${esc(x.notes||'No notes')}</span></div><button class="text-button danger-text" data-delete-receipt="${esc(x.id)}">Remove</button></div>`).join(''):'<div class="garage-empty compact">No receipts or maintenance purchases recorded.</div>'}
function maintenanceReport(){const v=selectedVehicle(),p=profileFor(),summary=maintenanceSummary(p),lines=[`ModPicker maintenance record — ${p.nickname||vehicleLabel(v)}`,`Vehicle: ${vehicleLabel(v)}`,`Odometer: ${p.odometer?`${Number(p.odometer).toLocaleString()} mi`:'not recorded'}`,`Condition: ${p.condition||'not recorded'}`,`Maintenance status: ${summary.due} due, ${summary.dueSoon} due soon, ${summary.unscheduled} unscheduled`,`Generated: ${new Date().toLocaleDateString()}`,''];lines.push('MAINTENANCE');if(!p.maintenance.length)lines.push('No maintenance items recorded.');for(const item of p.maintenance){const due=maintenanceDue(item,p);lines.push(`- ${item.name||'Service item'} | last: ${item.lastMileage||'—'} mi / ${item.lastDate||'—'} | next: ${due.dueMileage??'—'} mi / ${due.dueDate||'—'} | ${due.status}`);if(item.fluidSpec||item.capacity||item.parts)lines.push(`  spec/capacity/parts: ${[item.fluidSpec,item.capacity,item.parts].filter(Boolean).join(' | ')}`);if(item.notes)lines.push(`  notes: ${item.notes}`)}lines.push('','DIAGNOSTIC CODE HISTORY');for(const x of p.codes)lines.push(`- ${x.code} | ${x.date||'date unknown'} | ${x.mileage||'—'} mi | ${x.description||''} | ${x.resolution||''}`);if(!p.codes.length)lines.push('No codes recorded.');lines.push('','RECEIPTS / PURCHASES');for(const x of p.receipts)lines.push(`- ${x.date||'date unknown'} | ${x.vendor||'Receipt'} | ${x.amount?`$${Number(x.amount).toFixed(2)}`:'amount unknown'} | ${x.category||''} | ${x.notes||''}`);if(!p.receipts.length)lines.push('No receipts recorded.');return lines.join('\n');}
async function copyReport(){try{await navigator.clipboard.writeText(maintenanceReport());notify('Maintenance report copied.')}catch{notify('Could not access the clipboard.')}}
function applyRecommendationContext(){const p=profileFor();try{if(typeof state!=='undefined'){const allowed=['balanced','reliability','power','handling','track','budget'];state.goal=allowed.includes(p.primaryGoal)?p.primaryGoal:'balanced';if(typeof saveState==='function')saveState();if(typeof renderAll==='function')renderAll();if(typeof route==='function')route('catalog')}}catch{}notify('Garage preferences applied to the current catalog goal.');}
function exportGarage(){const payload={version:2,exportedAt:new Date().toISOString(),vehicleId:selectedVehicleId(),profile:profileFor()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`modpicker-garage-${selectedVehicleId()||'vehicle'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importGarage(file){try{const payload=JSON.parse(await file.text());if(!payload||typeof payload!=='object'||!payload.profile||typeof payload.profile!=='object')throw new Error('Invalid garage export');const vehicleId=payload.vehicleId||selectedVehicleId();if(!window.MODPICKER_DATA?.vehicles?.some(v=>v.id===vehicleId))throw new Error('Vehicle is not in this catalog');profiles[vehicleId]={...blankProfile(),...payload.profile,photos:Array.isArray(payload.profile.photos)?payload.profile.photos.slice(0,MAX_PHOTOS):[],maintenance:Array.isArray(payload.profile.maintenance)?payload.profile.maintenance:[],codes:Array.isArray(payload.profile.codes)?payload.profile.codes:[],receipts:Array.isArray(payload.profile.receipts)?payload.profile.receipts:[]};writeProfiles();if(vehicleId===selectedVehicleId())render();notify('Garage profile imported.')}catch(e){console.warn(e);notify('Could not import that Garage JSON file.')}}
function freshPrice(p){try{if(typeof lowestPrice==='function')return lowestPrice(p)}catch{}const offers=(p.offers||[]).filter(o=>Number.isFinite(Number(o.price))&&Number(o.price)>0);return offers.length?Math.min(...offers.map(o=>Number(o.price))):null}
function planScore(p,goal){const metric=GOAL_METRIC[goal]||'overall',value=p.rating?.[metric];return Number.isFinite(Number(value))?Number(value):-1}
function generatePlan(){
 const p=profileFor(),vid=selectedVehicleId(),all=(window.MODPICKER_DATA?.parts||[]).filter(x=>Array.isArray(x.vehicles)&&x.vehicles.includes(vid));
 const budget=numberOrNull(p.budget),goal=p.primaryGoal||'balanced';
 const maintenance=maintenanceSummary(p);const categories=new Set(),chosen=[];let spent=0;
 const sorted=[...all].sort((a,b)=>planScore(b,goal)-planScore(a,goal)||Number(Boolean(b.fitments?.length))-Number(Boolean(a.fitments?.length))||(freshPrice(a)??Infinity)-(freshPrice(b)??Infinity));
 for(const item of sorted){const price=freshPrice(item);if(categories.has(item.category))continue;if(budget!=null&&price!=null&&spent+price>budget)continue;chosen.push({id:item.id,name:item.name,brand:item.brand,category:item.category,price,score:planScore(item,goal),fitmentEvidence:Boolean(item.fitments?.length)});categories.add(item.category);if(price!=null)spent+=price;if(chosen.length>=4)break;}
 currentPlan=chosen;renderPlan();
 const note=maintenance.due||maintenance.dueSoon?' Maintenance due items are shown as a prerequisite warning.':'';notify(chosen.length?`Draft plan created from ${chosen.length} catalog categories.${note}`:'No compatible catalog parts are available for a draft plan.');
}
function renderPlan(){const root=$('#garageBuildPlan');if(!root)return;const p=profileFor(),summary=maintenanceSummary(p);if(!currentPlan.length){root.innerHTML='<div class="garage-empty compact">Generate a draft to get a budget-aware shortlist from the current exact-fitment catalog. It will not add unsupported horsepower estimates.</div>';return;}const known=currentPlan.filter(x=>x.price!=null).reduce((s,x)=>s+x.price,0),unknown=currentPlan.filter(x=>x.price==null).length;root.innerHTML=`${summary.due||summary.dueSoon?`<div class="plan-warning"><strong>Maintenance first:</strong> ${summary.due} due and ${summary.dueSoon} due-soon items are recorded. Resolve known weak points before treating performance upgrades as a complete plan.</div>`:''}<div class="plan-summary"><strong>${currentPlan.length} part draft</strong><span>${known?`Known prices about $${known.toLocaleString()}`:'No current prices available'}${unknown?` · ${unknown} price unknown`:''}</span></div>${currentPlan.map(x=>`<article class="plan-item"><div><span class="eyebrow">${esc(x.category||'Part')}</span><strong>${esc(x.brand||'')} ${esc(x.name||'')}</strong><small>${x.score>=0?`Goal metric ${x.score.toFixed(1)}/10`:'Goal metric not rated'} · ${x.fitmentEvidence?'fitment evidence attached':'confirm fitment evidence'}</small></div><span>${x.price==null?'Price unknown':`$${Number(x.price).toLocaleString()}`}</span></article>`).join('')}<p class="garage-note">This is a deterministic shortlist, not an AI horsepower forecast. It uses current catalog compatibility, available ratings and observed prices. Prerequisite/dependency modeling is still being expanded.</p>`;}
function addPlanToBuild(){if(!currentPlan.length)return notify('Generate a draft plan first.');try{if(typeof state==='undefined')throw new Error('Build state unavailable');let added=0;for(const item of currentPlan){if(!state.build.includes(item.id)){state.build.push(item.id);state.buildMeta[item.id]=state.buildMeta[item.id]||{status:'planned'};added++}}if(typeof saveState==='function')saveState();if(typeof renderAll==='function')renderAll();notify(added?`${added} planned parts added to the build sheet.`:'All draft parts are already in the build sheet.')}catch{notify('Could not add the draft to the build sheet.')}}
function bind(){
 document.querySelectorAll('[data-profile-field]').forEach(el=>el.addEventListener('input',fieldInput));
 $('#garagePhotoInput')?.addEventListener('change',e=>{addPhotos(e.target.files);e.target.value=''});$('#garagePhotos')?.addEventListener('click',e=>{const b=e.target.closest('[data-remove-photo]');if(!b)return;profileFor().photos.splice(Number(b.dataset.removePhoto),1);saveProfile();renderPhotos()});
 $('#addMaintenanceButton')?.addEventListener('click',()=>addMaintenance());$('#seedMaintenanceButton')?.addEventListener('click',seedMaintenance);
 $('#maintenanceList')?.addEventListener('input',updateMaintenance);$('#maintenanceList')?.addEventListener('change',updateMaintenance);$('#maintenanceList')?.addEventListener('click',e=>{const service=e.target.closest('[data-service-maint]');if(service)return markServiced(service.dataset.serviceMaint);const remove=e.target.closest('[data-delete-maint]');if(remove)deleteMaintenance(remove.dataset.deleteMaint)});
 $('#addCodeButton')?.addEventListener('click',addCode);$('#codeHistory')?.addEventListener('click',e=>{const b=e.target.closest('[data-delete-code]');if(!b)return;const p=profileFor();p.codes=p.codes.filter(x=>x.id!==b.dataset.deleteCode);saveProfile();renderCodes()});
 $('#addReceiptButton')?.addEventListener('click',addReceipt);$('#receiptHistory')?.addEventListener('click',e=>{const b=e.target.closest('[data-delete-receipt]');if(!b)return;const p=profileFor();p.receipts=p.receipts.filter(x=>x.id!==b.dataset.deleteReceipt);saveProfile();renderReceipts()});
 $('#copyMaintenanceReport')?.addEventListener('click',copyReport);$('#applyGarageContext')?.addEventListener('click',applyRecommendationContext);$('#exportGarageData')?.addEventListener('click',exportGarage);$('#importGarageButton')?.addEventListener('click',()=>$('#importGarageInput')?.click());$('#importGarageInput')?.addEventListener('change',e=>{const file=e.target.files?.[0];if(file)importGarage(file);e.target.value=''});$('#generateGaragePlan')?.addEventListener('click',generatePlan);$('#addGaragePlanToBuild')?.addEventListener('click',addPlanToBuild);
 document.querySelectorAll('[data-route="garage"]').forEach(el=>el.addEventListener('click',()=>setTimeout(render,0)));const vehicleName=$('#vehicleName');if(vehicleName)new MutationObserver(()=>{const current=selectedVehicleId();if(current!==lastVehicleId){currentPlan=[];render()}}).observe(vehicleName,{childList:true,subtree:true,characterData:true});
}
function init(){if(!$('#garageView'))return;bind();render();window.ModPickerGarage={getProfile:vehicleId=>structuredClone(profileFor(vehicleId)),getRecommendationContext:vehicleId=>structuredClone(recommendationContext(vehicleId)),getMaintenanceReport:maintenanceReport,getMaintenanceSummary:vehicleId=>structuredClone(maintenanceSummary(profileFor(vehicleId))),getContextCompleteness:vehicleId=>structuredClone(contextCompleteness(profileFor(vehicleId))),generatePlan:()=>{generatePlan();return structuredClone(currentPlan)},exportData:()=>structuredClone(profiles)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
