(()=>{
const DATA=window.MODPICKER_DATA;
const baseShowPart=window.showPart;
const enc=encodeURIComponent;
const communities={
 "z3-2000-28":{name:"Bimmerforums Z3",domain:"bimmerforums.com",hub:"https://www.bimmerforums.com/forum/forumdisplay.php?137-1996-2002-Z3-%28E36-7-E36-8%29"},
 "miata-1999":{name:"MX-5 Miata Forum",domain:"forum.miata.net",hub:"https://forum.miata.net/"},
 "brz-2017":{name:"FT86Club",domain:"ft86club.com",hub:"https://www.ft86club.com/forums/"},
 "e46-2003-330i":{name:"E46Fanatics",domain:"e46fanatics.com",hub:"https://www.e46fanatics.com/"},
 "mustang-2015-gt":{name:"Mustang6G",domain:"mustang6g.com",hub:"https://www.mustang6g.com/forums/"},
 "gti-2020":{name:"GolfMK7",domain:"golfmk7.com",hub:"https://www.golfmk7.com/forums/"}
};
const exactResources={
 "koyo-z3-rad":[
  {label:"Koyorad radiator information",type:"Manufacturer",url:"https://koyorad.com/radiators"},
  {label:"HH422674 product reference",type:"Retailer reference",url:"https://www.maperformance.com/products/koyo-radiator-1988-1999-bmw-3-series-m3-hh422674"},
  {label:"HH422674 Z3 fitment reference",type:"Retailer fitment",url:"https://www.tunersports.com/koyo-hh422674-racing-radiators-p87.html"}
 ]
};
const categoryGuides={
 Cooling:{tools:["Metric socket set","Pliers/hose-clamp tool","Drain pan","Funnel/bleeding equipment","Shop towels"],steps:["Confirm exact application and let the engine cool completely before opening the cooling system.","Disconnect or move intake, fan/shroud, undertray, or other components needed for access.","Drain coolant into a suitable container following the vehicle service procedure.","Disconnect hoses, sensors and mounting hardware while noting routing and connector locations.","Compare the replacement part with the removed part and transfer only the fittings required by the manufacturer.","Install the new component without forcing hoses or mounts; inspect adjacent hoses, seals and plastic fittings.","Refill with the correct coolant mixture and bleed the system using the vehicle-specific procedure.","Bring the vehicle to temperature, inspect for leaks, verify fan operation, then recheck coolant level after cool-down."]},
 Maintenance:{tools:["Metric hand tools","Torque wrench","Inspection light","Service fluids/consumables"],steps:["Confirm the maintenance item and replacement interval for the exact engine and production date.","Document existing routing, connectors and fluid levels before disassembly.","Remove surrounding components only as required for safe access.","Replace the service item and any single-use seals or hardware specified by the service information.","Reassemble carefully and use the manufacturer/service-manual torque procedure where required.","Start the vehicle, check for leaks or warning lights and verify normal operation."]},
 Brakes:{tools:["Jack and stands/lift","Wheel tools","Metric socket set","Caliper tool","Brake cleaner","Torque wrench","Bleeding equipment if hydraulic system is opened"],steps:["Verify pad, rotor, caliper and wheel-clearance fitment before disassembly.","Secure the vehicle on a lift or rated stands and remove the wheel.","Remove the caliper/bracket as required and support the caliper so the hose is not loaded.","Replace pads, rotors, lines or hardware according to the part-specific procedure; do not contaminate friction surfaces.","If any brake line or caliper hydraulic connection was opened, bleed the system using the vehicle service procedure.","Reinstall the wheel and tighten all fasteners to the official vehicle/component specification.","Before driving, establish a firm pedal and perform the pad/rotor bedding procedure specified by the manufacturer in a safe location."]},
 Suspension:{tools:["Jack and stands/lift","Metric socket set","Breaker bar","Torque wrench","Spring compressor when required","Alignment equipment/service"],steps:["Record ride height and current alignment-related settings before disassembly.","Secure the vehicle, remove the wheel and support the suspension so components are not loaded unexpectedly.","Disconnect links, dampers, strut mounts or control-arm hardware required by the specific component.","Use a proper spring compressor whenever a loaded conventional spring must be removed from a strut assembly.","Install the new component with orientation, preload and adjustment ranges set to the manufacturer baseline.","Tighten suspension bushings in the specified loaded position when the service information requires it.","Set ride height and damping evenly side-to-side, then obtain a professional alignment before performance driving."]},
 Chassis:{tools:["Jack and stands/lift","Metric hand tools","Torque wrench","Bushing puller/press when required","Paint marker"],steps:["Inspect the mounting area for cracks, corrosion or prior repair before installing a reinforcement or bushing.","Support the vehicle and affected subframe/suspension components safely.","Remove the original brace, bushing or mount using the correct puller/press method when required.","Clean and inspect the mounting surfaces before installing the replacement component.","Install with the supplied hardware and orientation; do not substitute torque values from unrelated applications.","Reassemble and obtain an alignment if suspension pickup points or bushings were disturbed."]},
 Intake:{tools:["Basic socket set","Screwdrivers/nut drivers","Pliers","Trim tools"],steps:["Confirm the intake is correct for the engine, MAF configuration and emissions requirements.","Document factory intake routing and disconnect sensors/connectors carefully.","Remove the factory airbox, ducting and clamps required for the kit.","Assemble the new intake and heat shield loosely, ensuring no tubing contacts belts, fans or hot exhaust components.","Reconnect all sensors and tighten clamps only after final alignment.","Start the engine and check for intake leaks, warning lights and abnormal fuel-trim behavior before hard driving."]},
 Exhaust:{tools:["Jack and stands/lift","Socket set","Penetrating oil","Exhaust hanger tool/pliers","Torque wrench"],steps:["Let the exhaust cool fully and verify the replacement system matches the chassis, engine and emissions configuration.","Raise the vehicle safely and apply penetrating oil to aged exhaust fasteners if needed.","Support exhaust sections before removing clamps, flanges and hangers.","Install the new system loosely from front to rear so tips, pipes and hangers can be aligned without stress.","Tighten hardware progressively once adequate clearance around the body, driveshaft and suspension is confirmed.","Start the engine and inspect all joints for leaks, rattles or contact after the first heat cycle."]},
 Drivetrain:{tools:["Lift preferred","Transmission jack when required","Metric socket set","Torque wrench","Fluid tools","Alignment tool when applicable"],steps:["Confirm compatibility with the transmission, flywheel, differential and existing power level.","Review the factory service procedure before beginning; many drivetrain jobs require supporting or removing major assemblies.","Drain fluids and disconnect linkage, driveshaft, hydraulic/electrical connections and mounts only as specified for the job.","Inspect adjacent seals, bearings, mounts and wear items while access is available.","Install and align the new component using the manufacturer-supplied procedure and any required specialty tools.","Refill fluids, bleed hydraulics if opened, and verify engagement/operation before road testing.","Follow any clutch or differential break-in requirements before hard use."]},
 Wheels:{tools:["Jack/lift","Wheel socket","Torque wrench","Fitment measuring tools"],steps:["Confirm diameter, width, offset, center bore, bolt pattern, brake clearance and tire compatibility.","Test-fit at least one front and rear wheel before mounting a full tire set when fitment is uncertain.","Have tires professionally mounted and balanced with suitable valve stems/sensors.","Install wheels on clean hub faces and tighten using the official vehicle/wheel hardware specification.","Check lock-to-lock steering and suspension/body clearance through the usable range of travel.","Recheck wheel hardware after the wheel/tire manufacturer’s recommended initial mileage."]},
 Tires:{tools:["Professional tire machine","Balancer","Tire-pressure gauge","Torque wrench"],steps:["Confirm tire size, load rating, speed rating and wheel-width compatibility.","Inspect wheel condition and valve stems/TPMS components before mounting.","Have tires mounted and dynamically balanced by suitable equipment.","Set cold pressures to an appropriate starting point for the vehicle and use case.","Verify clearance at full steering lock and through suspension travel.","For track use, monitor hot pressures and wear patterns rather than relying on street pressures."]},
 Ignition:{tools:["Socket set","Spark-plug socket","Extension","Torque wrench","Compressed air/cleaning tools"],steps:["Work on a cool engine and confirm the correct plug/coil application.","Clean debris away from plug wells before removing coils or plugs.","Disconnect coils carefully and inspect boots, connectors and plug wells for oil or moisture.","Install plugs with the gap/specification required for the exact engine and tune; use the official torque procedure.","Reinstall coils/connectors and verify smooth operation with no misfire faults."]},
 Tuning:{tools:["Battery charger/support unit","Laptop or flashing device","Diagnostic/logging software"],steps:["Confirm the tune is intended for the exact ECU strategy, fuel octane, hardware and emissions configuration.","Connect stable battery support before any ECU flash.","Save stock calibration information when the platform/tool supports it.","Flash the calibration exactly as instructed without interrupting vehicle power or communications.","Clear/adapt values only when instructed, then start the vehicle and inspect for fault codes.","Log the parameters requested by the tuner and avoid hard use until the calibration is validated."]},
 "Forced Induction":{tools:["Professional-level hand tools","Torque wrench","Cooling/fluid tools","Diagnostic/logging equipment","Fabrication tools depending on kit"],steps:["Treat forced induction as a system-level modification: confirm engine health, fuel system, clutch/transmission, cooling and tuning requirements first.","Inventory the complete kit and supporting modifications before disassembly.","Follow the kit manufacturer’s installation manual rather than a generic sequence; routing, belt drive, oil supply and charge plumbing vary substantially.","Pressure-test charge plumbing and inspect all fluid connections before starting the engine.","Load the correct calibration and verify fuel pressure, air/fuel behavior, boost control and temperatures with suitable logging.","Use conservative initial testing and professional inspection/tuning before full-load operation."]}
};
const fallbackGuide={tools:["Vehicle-specific service information","Basic hand tools","Torque wrench","Safety equipment"],steps:["Verify exact part number and vehicle fitment before starting.","Read the manufacturer installation instructions and relevant factory service procedure completely.","Photograph or label connectors, routing and fastener locations before disassembly.","Remove only the components required for safe access.","Install the new part using the manufacturer’s sequence and official torque specifications.","Inspect clearances, connections and fluid levels before startup.","Test at low load first, re-inspect the installation, then perform any alignment, bleeding, calibration or bedding procedure the job requires."]};
function part(id){return DATA.parts.find(p=>p.id===id)}
function vehicleForPart(p){return DATA.vehicles.find(v=>p.vehicles.includes(v.id))||DATA.vehicles[0]}
function qurl(query){return `https://www.google.com/search?q=${enc(query)}`}
function yt(query){return `https://www.youtube.com/results?search_query=${enc(query)}`}
function reddit(query){return `https://www.reddit.com/search/?q=${enc(query)}`}
function images(query){return `https://www.google.com/search?tbm=isch&q=${enc(query)}`}
function researchLinks(p,v){const c=communities[v.id],query=`${v.year} ${v.make} ${v.model} ${p.brand} ${p.name}`;const links=[
 {label:"Forum discussions",meta:c?c.name:"Vehicle forums",url:c?qurl(`site:${c.domain} ${p.brand} ${p.name} ${v.model}`):qurl(`${query} forum discussion`)},
 {label:"Reddit discussions",meta:"Owner experiences",url:reddit(`${p.brand} ${p.name} ${v.make} ${v.model}`)},
 {label:"Install videos",meta:"YouTube search",url:yt(`${query} install`)},
 {label:"Photos & installed examples",meta:"Image search",url:images(`${query} installed`)},
 {label:"Installation guides / PDFs",meta:"Manual & PDF search",url:qurl(`"${p.brand}" "${p.name}" installation instructions filetype:pdf`)},
 {label:"Manufacturer information",meta:"Official/product search",url:qurl(`${p.brand} ${p.name} manufacturer`)}
 ];return links}
function augment(id){const p=part(id);if(!p)return;const v=vehicleForPart(p),c=communities[v.id],guide=categoryGuides[p.category]||fallbackGuide,links=researchLinks(p,v),exact=exactResources[id]||[],root=document.querySelector("#partDialogContent");if(!root)return;root.insertAdjacentHTML("beforeend",`<section class="research-panel"><span class="eyebrow">Research center</span><h3>Discussions, install information, photos & guides</h3><p class="muted">These links are intentionally separated by source type. Community discussions can expose real-world fitment and reliability experiences, but they are not substitutes for manufacturer or factory service instructions.</p>${c?`<div class="community-hub"><div><strong>${c.name}</strong><small>Vehicle-specific community hub for ${v.make} ${v.model}</small></div><a class="button secondary small" href="${c.hub}" target="_blank" rel="noopener">Open forum</a></div>`:''}<div class="research-links">${links.map(x=>`<a class="research-link" href="${x.url}" target="_blank" rel="noopener"><span>${x.label}</span><small>${x.meta} ↗</small></a>`).join('')}</div>${exact.length?`<h4>Specific product references</h4><div class="research-links">${exact.map(x=>`<a class="research-link" href="${x.url}" target="_blank" rel="noopener"><span>${x.label}</span><small>${x.type} ↗</small></a>`).join('')}</div>`:''}<h4>Install planning sequence</h4><div class="research-warning">Planning guide only. Before installation, use the exact part manufacturer instructions and the vehicle’s factory/service information for torque values, fluid procedures, lifting points, alignment settings, calibration and safety-critical steps.</div><div class="install-plan">${guide.steps.map(x=>`<div class="install-step">${x}</div>`).join('')}</div><h4>Typical tools / resources</h4><div class="tools-list">${guide.tools.map(x=>`<span class="tool-chip">${x}</span>`).join('')}</div></section>`)}
window.showPart=function(id){baseShowPart(id);augment(id)};
})();
