(()=>{
'use strict';
function loadCss(){if(document.querySelector('link[href="site-refresh.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='site-refresh.css';document.head.appendChild(link)}
function setNavLabel(route,label){const el=document.querySelector(`.main-nav [data-route="${route}"]`);if(!el)return;const nodes=[...el.childNodes];const text=nodes.find(n=>n.nodeType===Node.TEXT_NODE);if(text)text.nodeValue=`${label} `;else el.prepend(document.createTextNode(`${label} `))}
function routeButton(label,route,className='button secondary'){const b=document.createElement('button');b.type='button';b.className=className;b.textContent=label;b.addEventListener('click',()=>typeof window.route==='function'&&window.route(route));return b}
function simplifyHero(){const hero=document.querySelector('#catalogView .hero');if(!hero||hero.dataset.cleaned)return;hero.dataset.cleaned='1';const copy=hero.firstElementChild;if(copy){const eyebrow=copy.querySelector('.eyebrow'),h1=copy.querySelector('h1'),p=copy.querySelector('p');if(eyebrow)eyebrow.textContent='Parts, fitment and build planning';if(h1)h1.innerHTML='Parts that fit.<br>Builds that make sense.';if(p)p.textContent='Choose your car, compare source-backed fitment and pricing, then save the parts you actually want to use.';const actions=document.createElement('div');actions.className='home-actions';actions.append(routeButton('Open my garage','garage','button primary'),routeButton('Plan my build','build'),routeButton('Compare prices','prices','button quiet'));copy.appendChild(actions)}const labels=['compatible parts','categories','recent offers'];hero.querySelectorAll('.hero-stats>div').forEach((d,i)=>{const s=d.querySelector('span');if(s&&labels[i])s.textContent=labels[i]})}
function simplifyBanner(){const b=document.querySelector('.prototype-banner');if(!b||b.dataset.cleaned)return;b.dataset.cleaned='1';b.innerHTML='<strong>Evidence-first catalog.</strong> Fitment, ratings and prices keep their source context. <a href="data-status.html">Data status</a>'}
function simplifyPageHeads(){const map={prices:['Compare prices','Recent seller observations for compatible parts. Verify stock, shipping and final checkout price with the seller.'],rankings:['Compare ratings','Published review evidence for compatible products. Missing evidence stays unrated.'],compare:['Compare parts','Put compatible parts side by side without losing fitment or pricing context.']};for(const [route,[title,copy]] of Object.entries(map)){const view=document.querySelector(`#${route}View`);if(!view)continue;const h=view.querySelector('.page-head h1'),p=view.querySelector('.page-head p');if(h)h.textContent=title;if(p)p.textContent=copy}}
function tuneNav(){setNavLabel('prices','Prices');setNavLabel('rankings','Ratings');setNavLabel('build','Build')}
function init(){loadCss();document.body.classList.add('ui-refresh');tuneNav();simplifyHero();simplifyBanner();simplifyPageHeads();document.documentElement.dataset.modpickerUi='refresh-v1'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
