/* Run with Playwright installed; CHROME_PATH optionally selects a local Chromium. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const server=spawn('python',['-m','http.server','8123'],{cwd:path.join(__dirname,'..'),stdio:'ignore'});
(async()=>{let browser;try{
await new Promise(r=>setTimeout(r,400));
browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('https://pzxofwrdidvqhdlqbehk.supabase.co/**',r=>r.abort());
await page.goto('http://localhost:8123');assert.equal(await page.locator('#vehicleSelect').count(),0);assert.ok(await page.locator('#makeSelect').count());assert.ok(await page.locator('#modelSelect').count());assert.ok(await page.locator('#yearSelect').count());assert.ok(await page.locator('#variantSelect').count());const makeLabels=await page.locator('#makeSelect option').allTextContents();assert.equal(new Set(makeLabels.map(x=>x.toLowerCase())).size,makeLabels.length);assert.ok(await page.locator('.part-card').count()>0);
await page.locator('.part-card .button.primary').first().click();await page.locator('[data-route="build"]').click();
await page.locator('.item-note input').fill('Manual torque spec — α <test>');await page.locator('.item-note input').dispatchEvent('change');
await page.locator('[aria-label^="Quantity"]').fill('2');await page.locator('[aria-label^="Quantity"]').dispatchEvent('change');
await page.locator('.item-fields input[step="0.01"]').fill('125');await page.locator('.item-fields input[step="0.01"]').dispatchEvent('change');
assert.equal(await page.locator('#buildPartsTotal').textContent(),'$250');
await page.selectOption('#makeSelect','Mazda');assert.equal(await page.inputValue('#modelSelect'),'MX-5 Miata');await page.selectOption('#modelSelect','MX-5 Miata');await page.selectOption('#yearSelect','1999');assert.equal(await page.locator('.item-note').count(),0);await page.selectOption('#makeSelect','BMW');await page.selectOption('#modelSelect','Z3');await page.selectOption('#yearSelect','2000');await page.selectOption('#variantSelect','z3-2000-28');
assert.equal(await page.locator('.item-note input').inputValue(),'Manual torque spec — α <test>');assert.equal(await page.locator('[aria-label^="Quantity"]').inputValue(),'2');
await page.reload();assert.equal(await page.locator('#buildPartsTotal').textContent(),'$250');
const payload=await page.evaluate(()=>buildPayload());const shared=Buffer.from(JSON.stringify(payload),'utf8').toString('base64');
await page.goto('http://localhost:8123/?build='+encodeURIComponent(shared));assert.equal(await page.locator('.item-note input').inputValue(),payload.buildMeta[payload.build[0]].note);
await page.locator('.build-item .button.danger').click();assert.equal(await page.locator('.build-item.polished').count(),0);await page.getByRole('button',{name:'Undo last change'}).click();assert.equal(await page.locator('.build-item.polished').count(),1);
await page.locator('#platformModeButton').click();assert.equal(await page.locator('#platformSelectors').getAttribute('hidden'),null);assert.equal(await page.locator('#platformSelectors').isVisible(),true);assert.equal(await page.locator('#vehicleSelectors').isVisible(),false);await page.selectOption('#platformMakeSelect','BMW');await page.selectOption('#platformSelect','bmw-m52tu');assert.equal(await page.inputValue('#platformApplicationSelect'),'z3-2000-28');assert.ok(await page.locator('.part-card').count()>0);assert.ok(await page.getByText('Platform-related result').count()>0);await page.selectOption('#platformMakeSelect','Mazda');assert.equal(await page.inputValue('#platformSelect'),'mazda-bp-4w');assert.equal(await page.inputValue('#platformApplicationSelect'),'miata-1999');assert.match(await page.locator('#vehicleName').textContent(),/Mazda/);await page.selectOption('#platformMakeSelect','BMW');assert.equal(await page.inputValue('#platformSelect'),'bmw-m52tu');await page.locator('#vehicleModeButton').click();assert.equal(await page.locator('#vehicleSelectors').isVisible(),true);assert.equal(await page.locator('#platformSelectors').isVisible(),false);await page.locator('.text-button').first().click();assert.ok(await page.locator('#partDialog').isVisible());assert.ok(await page.getByText('Where the rating comes from').isVisible());await page.locator('#dialogClose').click();
await page.evaluate(async p=>{await importBuild(new File([JSON.stringify(p)],'build.json',{type:'application/json'}))},payload);assert.equal(await page.locator('#buildPartsTotal').textContent(),'$250');
await page.evaluate(()=>{const p=part(state.build[0]);state.compare=[p.id];renderCompare()});
for(const route of ['catalog','prices','rankings','compare','build'])await page.evaluate(r=>window.route(r,false),route);
await page.locator('#applicationSearch').fill('M52TU');assert.ok(await page.locator('#applicationResults button').count()>0);await page.locator('#applicationSearch').fill('Z3 2000');assert.ok(await page.locator('#applicationResults button').count()>1);await page.locator('#applicationSearch').fill('');
await page.evaluate(()=>{const p=part('miata-koni-active');const f=p.fitments.find(f=>f.vehicle_id.startsWith('epa-'));state.browseMode='vehicle';switchVehicle(f.vehicle_id);window.showPart(p.id)});assert.ok(await page.getByText(/Incompatible with stock|Incompatible|incompatible|Mazdaspeed/, {exact:false}).count()>0);await page.locator('#dialogClose').click();await page.evaluate(async p=>importBuild(new File([JSON.stringify(p)],'build.json',{type:'application/json'})),payload);
await page.screenshot({path:'/tmp/modpicker-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});
assert.ok(await page.locator('.build-item .button.danger').isVisible(),'Mobile removal control must remain visible');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:'/tmp/modpicker-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: browser persistence, multi-vehicle builds, quantities/costs, Unicode sharing, undo, import, details, all routes and mobile layout.');
}finally{await browser?.close();server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
