/* Run with Playwright installed; CHROME_PATH optionally selects a local Chromium. */
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const path=require('node:path');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'):'playwright');
const server=spawn('python',['-m','http.server','8123'],{cwd:path.join(__dirname,'..'),stdio:'ignore'});
(async()=>{let browser;try{
await new Promise(r=>setTimeout(r,400));
browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('https://pzxofwrdidvqhdlqbehk.supabase.co/**',r=>r.abort());
await page.goto('http://localhost:8123');assert.equal(await page.locator('#vehicleSelect').count(),0);assert.ok(await page.locator('#makeSelect').count());assert.ok(await page.locator('#modelSelect').count());assert.ok(await page.locator('#yearSelect').count());assert.ok(await page.locator('#variantSelect').count());const makeLabels=await page.locator('#makeSelect option').allTextContents();assert.equal(new Set(makeLabels.map(x=>x.toLowerCase())).size,makeLabels.length);assert.ok(await page.locator('.part-card').count()>0);
await page.locator('.part-card .button.primary').first().click();await page.locator('[data-route="build"]').click();
await page.locator('.item-note input').fill('Manual torque spec — α <test>');await page.locator('.item-note input').dispatchEvent('change');
await page.locator('[aria-label^="Quantity"]').fill('2');await page.locator('[aria-label^="Quantity"]').dispatchEvent('change');
await page.locator('.item-fields input[step="0.01"]').fill('125');await page.locator('.item-fields input[step="0.01"]').dispatchEvent('change');
assert.equal(await page.locator('#buildPartsTotal').textContent(),'$250');
await page.selectOption('#makeSelect','Mazda');assert.equal(await page.inputValue('#modelSelect'),'MX-5 Miata');await page.selectOption('#modelSelect','MX-5 Miata');await page.selectOption('#yearSelect','1999');assert.equal(await page.locator('.item-note').count(),0);await page.selectOption('#makeSelect','BMW');await page.selectOption('#modelSelect','Z3');await page.selectOption('#yearSelect','2000');await page.selectOption('#variantSelect','z3-2000-28');
assert.equal(await page.locator('.item-note input').inputValue(),'Manual torque spec — α <test>');assert.equal(await page.locator('[aria-label^="Quantity"]').inputValue(),'2');
await page.reload();assert.equal(await page.locator('#buildPartsTotal').textContent(),'$250');
const payload=await page.evaluate(()=>buildPayload());const shared=Buffer.from(JSON.stringify(payload),'utf8').toString('base64');
await page.goto('http://localhost:8123/?build='+encodeURIComponent(shared));assert.equal(await page.locator('.item-note input').inputValue(),payload.buildMeta[payload.build[0]].note);
await page.locator('.build-item .button.danger').click();assert.equal(await page.locator('.build-item.polished').count(),0);await page.getByRole('button',{name:'Undo last change'}).click();assert.equal(await page.locator('.build-item.polished').count(),1);
await page.locator('#platformModeButton').click();assert.equal(await page.locator('#platformSelectors').getAttribute('hidden'),null);assert.equal(await page.locator('#platformSelectors').isVisible(),true);assert.equal(await page.locator('#vehicleSelectors').isVisible(),false);await page.selectOption('#platformMakeSelect','BMW');await page.selectOption('#platformSelect','bmw-m52tu');assert.equal(await page.inputValue('#platformApplicationSelect'),'z3-2000-28');assert.ok(await page.locator('.part-card').count()>0);assert.ok(await page.getByText('Platform-related result').count()>0);await page.selectOption('#platformMakeSelect','Mazda');assert.equal(await page.inputValue('#platformSelect'),'mazda-bp-4w');assert.equal(await page.inputValue('#platformApplicationSelect'),'miata-1999');assert.match(await page.locator('#vehicleName').textContent(),/Mazda/);await page.selectOption('#platformMakeSelect','BMW');assert.equal(await page.inputValue('#platformSelect'),'bmw-m52tu');await page.locator('#vehicleModeButton').click();assert.equal(await page.locator('#vehicleSelectors').isVisible(),true);assert.equal(await page.locator('#platformSelectors').isVisible(),false);await page.locator('.text-button').first().click();assert.ok(await page.locator('#partDialog').isVisible());assert.ok(await page.getByText('Where the rating comes from').isVisible());await page.locator('#dialogClose').click();
await page.evaluate(async p=>{await importBuild(new File([JSON.stringify(p)],'build.json',{type:'application/json'}))},payload);assert.equal(await page.locator('#buildPartsTotal').textContent(),'$250');
await page.evaluate(()=>{const p=part(state.build[0]);state.compare=[p.id];renderCompare()});
for(const route of ['catalog','prices','rankings','compare','build'])await page.evaluate(r=>window.route(r,false),route);
await page.locator('#applicationSearch').fill('M52TU');assert.ok(await page.locator('#applicationResults button').count()>0);await page.locator('#applicationSearch').fill('Z3 2000');assert.ok(await page.locator('#applicationResults button').count()>1);await page.locator('#applicationSearch').fill('');
await page.evaluate(()=>{const p=part('miata-koni-active');const f=p.fitments.find(f=>f.vehicle_id.startsWith('epa-'));state.browseMode='vehicle';switchVehicle(f.vehicle_id);window.showPart(p.id)});assert.ok(await page.getByText(/Incompatible with stock|Incompatible|incompatible|Mazdaspeed/, {exact:false}).count()>0);await page.locator('#dialogClose').click();await page.evaluate(async p=>importBuild(new File([JSON.stringify(p)],'build.json',{type:'application/json'})),payload);

await page.waitForSelector('[data-route="garage"]');await page.locator('[data-route="garage"]').click();await page.waitForSelector('#garageView.active-view');
await page.locator('#garageNickname').fill('Smoke Test Z3');await page.locator('#garageNickname').dispatchEvent('input');
await page.locator('#garageOdometer').fill('100000');await page.locator('#garageOdometer').dispatchEvent('input');
await page.locator('#garageBudget').fill('1800');await page.locator('#garageBudget').dispatchEvent('input');
await page.selectOption('#garagePrimaryGoal','reliability');await page.locator('#garagePrimaryGoal').dispatchEvent('input');
await page.locator('#garageBuildGoals').fill('Reliable street car with preventive maintenance first.');await page.locator('#garageBuildGoals').dispatchEvent('input');
await page.locator('#seedMaintenanceButton').click();assert.ok(await page.locator('.maintenance-card').count()>=10);
const firstMaint=page.locator('.maintenance-card').first();await firstMaint.locator('[data-maint-field="lastMileage"]').fill('90000');await firstMaint.locator('[data-maint-field="lastMileage"]').dispatchEvent('change');await firstMaint.locator('[data-maint-field="intervalMiles"]').fill('5000');await firstMaint.locator('[data-maint-field="intervalMiles"]').dispatchEvent('change');assert.equal(await firstMaint.locator('.maintenance-status').textContent(),'Due');
await page.locator('#codeValue').fill('P0171');await page.locator('#codeDescription').fill('Lean condition');await page.locator('#addCodeButton').click();assert.match(await page.locator('#codeHistory').textContent(),/P0171/);
await page.locator('#receiptVendor').fill('Test Parts');await page.locator('#receiptAmount').fill('42.50');await page.locator('#receiptNotes').fill('Oil and filter');await page.locator('#addReceiptButton').click();assert.match(await page.locator('#receiptHistory').textContent(),/Test Parts/);
await page.waitForFunction(()=>window.ModPickerPlanner&&window.ModPickerGarage);
const plannerAudit=await page.evaluate(()=>{const plan=window.ModPickerPlanner.choosePlan(),ids=new Set([...state.build,...plan.picks.map(p=>p.id)]);let missing=0,conflicts=0;for(const p of plan.picks){missing+=(p.requires||[]).filter(id=>!ids.has(id)).length;conflicts+=(p.conflicts||[]).filter(id=>ids.has(id)).length;for(const id of ids)if(part(id)?.conflicts?.includes(p.id))conflicts++}return{missing,conflicts,count:plan.picks.length}});assert.equal(plannerAudit.missing,0);assert.equal(plannerAudit.conflicts,0);
const prePlanCount=await page.evaluate(()=>state.build.length);await page.locator('#generateGaragePlan').click();assert.match(await page.locator('#garageBuildPlan').textContent(),/part draft|No additional/);if(plannerAudit.count){await page.locator('#addGaragePlanToBuild').click();await page.waitForFunction(({before,count})=>state.build.length>=before+count,{before:prePlanCount,count:plannerAudit.count});assert.ok(await page.locator('#buildView.active-view').count());assert.equal(await page.inputValue('#budgetInput'),'1800');assert.ok(await page.evaluate(()=>buildTotals().subtotal<=state.budget),'Starter plan must respect parts budget including existing quantities and paid overrides')}
await page.reload();await page.waitForSelector('[data-route="garage"]');await page.locator('[data-route="garage"]').click();assert.equal(await page.inputValue('#garageNickname'),'Smoke Test Z3');assert.match(await page.locator('#codeHistory').textContent(),/P0171/);assert.match(await page.locator('#receiptHistory').textContent(),/Test Parts/);

await page.evaluate(()=>{state.browseMode='vehicle';switchVehicle('brz-2017');window.showPart('brz-perrin-master-brace')});await page.waitForSelector('.interchange-detail');assert.match(await page.locator('.interchange-detail').textContent(),/Scion FR-S/);assert.match(await page.locator('.interchange-detail').textContent(),/Toyota 86/);assert.match(await page.locator('.interchange-detail').textContent(),/GR86/);await page.locator('#dialogClose').click();
await page.evaluate(()=>{state.browseMode='vehicle';switchVehicle('z3-2000-28')});

await page.evaluate(()=>window.route('build',false));await page.screenshot({path:'/tmp/modpicker-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});
assert.ok(await page.locator('.build-item .button.danger').isVisible(),'Mobile removal control must remain visible');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.evaluate(()=>window.route('catalog',false));await page.waitForSelector('.filter-advanced-toggle');assert.ok(await page.locator('.filter-advanced-toggle').isVisible(),'Mobile More filters control must be visible');assert.equal(await page.locator('#difficultyFilter').isVisible(),false,'Advanced mobile filters should begin collapsed');await page.locator('.filter-advanced-toggle').click();assert.equal(await page.locator('.filter-advanced-toggle').getAttribute('aria-expanded'),'true');assert.ok(await page.locator('#difficultyFilter').isVisible(),'Advanced filters must become visible after expansion');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:'/tmp/modpicker-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('PASS: browser persistence, multi-vehicle builds, Garage maintenance/profile persistence, dependency-aware starter planning, interchange evidence, quantities/costs, Unicode sharing, undo, import, details, collapsible mobile filters and mobile layout.');
}finally{await browser?.close();server.kill()}})().catch(e=>{console.error(e);process.exitCode=1});
